//! Test-only reader for the C0 reference fixture.
//!
//! `opm/compositional/ptflash_fixtures.json` is generated by `tools/opm_compositional/` from the
//! installed OPM 2026.04 headers; see `docs/COMPOSITIONAL_VALIDATION.md` §3a. This module gives
//! C2–C5 a typed view of it so each task compares against the same parsed numbers rather than
//! writing its own ad-hoc extraction.
//!
//! The file is embedded with `include_str!`, so a test run cannot silently pick up a stale or
//! missing copy, and the fixture's own `--check` regeneration gate is what keeps it honest.
//!
//! **The fixture is an oracle, not a specification.** Where it and this crate disagree about a
//! convention, the conversion is explicit and named — see [`FixturePhase::molar_density_si`] for
//! the gas-constant one — never absorbed into a tolerance.

#![cfg(test)]

use serde::Deserialize;

/// The whole fixture.
#[derive(Debug, Deserialize)]
pub struct Fixture {
    pub schema: String,
    pub eos: String,
    pub flash_tolerance: f64,
    pub systems: Vec<FixtureSystem>,
}

#[derive(Debug, Deserialize)]
pub struct FixtureSystem {
    pub system: String,
    pub num_components: usize,
    pub components: Vec<FixtureComponent>,
    pub binary_interaction: Vec<Vec<f64>>,
    /// Flash-free EOS evaluations. See [`FixtureEosState`].
    pub eos_states: Vec<FixtureEosState>,
    pub states: Vec<FixtureState>,
}

/// One direct EOS evaluation at a given `(p, T, x)`, with no flash and therefore no stability
/// claim of any kind.
///
/// These exist because none of the flashed states has three real roots — at 150 °C every one of
/// them is monotonic — so without this section a port could get the root-labelling rule entirely
/// wrong and still reproduce the whole fixture. They also cover pure components, which PTFlash
/// cannot flash at all (`z_i = 0` breaks Michelsen's test) but the EOS evaluates without
/// difficulty.
///
/// `smallest_root` and `largest_root` are the two extreme roots of one cubic, read off OPM by
/// asking its parameter cache for the oil-phase and gas-phase molar volume at the same
/// composition. When the cubic has a single real root the two are identical, which is itself a
/// contract worth testing.
#[derive(Debug, Deserialize)]
pub struct FixtureEosState {
    pub id: String,
    pub status: String,
    pub note: String,
    pub pressure_pa: f64,
    pub temperature_k: f64,
    pub x: Vec<f64>,
    pub eos_A: Option<f64>,
    pub eos_B: Option<f64>,
    pub smallest_root: Option<FixtureRoot>,
    pub largest_root: Option<FixtureRoot>,
}

#[derive(Debug, Deserialize)]
pub struct FixtureRoot {
    pub molar_volume: f64,
    pub molar_density: f64,
    pub mass_density: f64,
    pub z_factor: f64,
    pub fugacity_coefficient: Vec<f64>,
}

impl FixtureEosState {
    /// True when the cubic has three real roots that are genuinely distinct — the case C2 must
    /// not mistake for two coexisting phases.
    pub fn has_distinct_roots(&self) -> bool {
        match (&self.smallest_root, &self.largest_root) {
            (Some(s), Some(l)) => (l.z_factor - s.z_factor).abs() > 1e-6,
            _ => false,
        }
    }
}

impl FixtureRoot {
    /// Molar density corrected from OPM's `R` to the SI one. See [`FixturePhase::molar_density_si`].
    pub fn molar_density_si(&self) -> f64 {
        super::units::opm_density_to_si(self.molar_density)
    }
}

#[derive(Debug, Deserialize)]
pub struct FixtureComponent {
    pub index: usize,
    pub name: String,
    pub molar_mass_kg_per_mol: f64,
    pub critical_temperature_k: f64,
    pub critical_pressure_pa: f64,
    pub critical_volume_m3_per_kmol: f64,
    pub acentric_factor: f64,
}

#[derive(Debug, Deserialize)]
pub struct FixtureState {
    pub id: String,
    pub status: String,
    pub method_used: String,
    pub pressure_pa: f64,
    pub temperature_k: f64,
    pub z: Vec<f64>,
    pub present_phase: String,
    pub single_phase: Option<bool>,
    #[serde(rename = "L_liquid")]
    pub l_liquid: Option<f64>,
    #[serde(rename = "beta_vapour")]
    pub beta_vapour: Option<f64>,
    #[serde(rename = "x_liquid")]
    pub x_liquid: Option<Vec<f64>>,
    #[serde(rename = "y_vapour")]
    pub y_vapour: Option<Vec<f64>>,
    #[serde(rename = "dL_liquid_du")]
    pub dl_liquid_du: Option<Vec<f64>>,
    #[serde(rename = "dx_liquid_du")]
    pub dx_liquid_du: Option<Vec<Vec<f64>>>,
    #[serde(rename = "dy_vapour_du")]
    pub dy_vapour_du: Option<Vec<Vec<f64>>>,
    pub liquid: Option<FixturePhase>,
    pub vapour: Option<FixturePhase>,
}

#[derive(Debug, Deserialize)]
pub struct FixturePhase {
    pub molar_volume: f64,
    pub molar_density: f64,
    pub mass_density: f64,
    pub z_factor: f64,
    pub eos_A: f64,
    pub eos_B: f64,
    pub viscosity: f64,
    pub fugacity_coefficient: Vec<f64>,
    pub dmolar_density_du: Vec<f64>,
    pub dmass_density_du: Vec<f64>,
    pub dviscosity_du: Vec<f64>,
}

impl FixturePhase {
    /// Molar density corrected from OPM's `R` to the SI one.
    ///
    /// Density is `p / (Z R T)`, so the correction is an exact scalar factor rather than an error
    /// band. `Z`, `eos_A`, `eos_B` and the fugacity coefficients need no correction — none of them
    /// contains `R`.
    pub fn molar_density_si(&self) -> f64 {
        super::units::opm_density_to_si(self.molar_density)
    }

    /// Mass density corrected from OPM's `R` to the SI one.
    pub fn mass_density_si(&self) -> f64 {
        super::units::opm_density_to_si(self.mass_density)
    }

    /// Molar volume corrected from OPM's `R` to the SI one.
    pub fn molar_volume_si(&self) -> f64 {
        super::units::opm_molar_volume_to_si(self.molar_volume)
    }
}

impl FixtureState {
    /// The phase composition to hand the EOS for a given branch.
    ///
    /// In a single-phase state PTFlash writes the overall composition into both phase slots, so
    /// both branches evaluate at `z` — which is what makes such a state a test that two algebraic
    /// roots are not two coexisting phases.
    pub fn composition_for(&self, liquid: bool) -> &[f64] {
        let c = if liquid {
            &self.x_liquid
        } else {
            &self.y_vapour
        };
        c.as_ref().map(|v| v.as_slice()).unwrap_or(&self.z)
    }

    pub fn is_two_phase(&self) -> bool {
        self.present_phase == "two_phase"
    }
}

/// Parse the committed fixture.
pub fn load() -> Fixture {
    let raw = include_str!("../../../../../opm/compositional/ptflash_fixtures.json");
    let fixture: Fixture = serde_json::from_str(raw).expect("C0 fixture must parse");
    assert_eq!(
        fixture.schema, "ressim-compositional-ptflash-fixture/2",
        "fixture schema changed; update this reader deliberately rather than loosening the check"
    );
    assert_eq!(fixture.eos, "PR", "V1 pins unmodified Peng-Robinson");
    assert_eq!(
        fixture.systems.len(),
        2,
        "expected the binary and ternary systems"
    );
    fixture
}

/// The binary (C1/C10) system.
pub fn binary_system(f: &Fixture) -> &FixtureSystem {
    f.systems
        .iter()
        .find(|s| s.num_components == 2)
        .expect("binary system")
}

/// The ternary (CO2/C1/C10) system.
pub fn ternary_system(f: &Fixture) -> &FixtureSystem {
    f.systems
        .iter()
        .find(|s| s.num_components == 3)
        .expect("ternary system")
}
