import type { Scenario } from '../scenarios';

export const dep_decline: Scenario = {
    key: 'dep_decline',
    label: 'Rate Decline',
    description: 'Constant-BHP production from a finite reservoir. PI sets the initial rate level; total compressibility c_t sets the decline duration. Displayed on log-time axes to reveal the exponential trend.',
    analyticalMethodSummary: 'Fetkovich exponential decline — rate and recovery reference curves for constant-BHP depletion, updated for active skin and permeability.',
    analyticalMethodReference: 'Fetkovich (1971).',
    scenarioClass: 'depletion',
    domain: 'depletion',
    chartPreset: 'fetkovich',
    defaultSensitivityDimensionKey: 'permeability',
    capabilities: {
        analyticalMethod: 'depletion',
        primaryRateCurve: 'oil-rate',
        showSweepPanel: false,
        analyticalNativeXAxis: 'time',
        hasTauDimensionlessTime: true,
        hasInjector: false,
        default3DScalar: null,
        requiresThreePhaseMode: false,
    },
    params: {
        analyticalSolutionMode: 'depletion',
        // Fluid
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / rel perm
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 1D slab 48 cells × 1 × 1, 480 m × 10 m × 10 m
        // High initial pressure + low BHP → drives exponential decline
        // Peaceman r_eq ≈ 1.98 m for 10×10 m cells; skin = -2 safe minimum
        // (ln(r_eq/r_w) ≈ 2.99; denominator = 2.99 + skin must remain > 0)
        nx: 48,
        ny: 1,
        nz: 1,
        cellDx: 10,
        cellDy: 10,
        cellDz: 10,
        permMode: 'uniform',
        uniformPermX: 20,
        uniformPermY: 20,
        uniformPermZ: 2,
        // Initial conditions: high pressure reservoir depleting to low BHP
        initialPressure: 1500,
        initialSaturation: 0.1,
        // Wells: single producer, no injector
        injectorEnabled: false,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 50,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 47,
        producerJ: 0,
        well_radius: 0.1,
        well_skin: 0,
        // Numerics
        delta_t_days: 0.25,
        steps: 250,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        gravityEnabled: false,
    },
    sensitivities: [
        {
            key: 'permeability',
            label: 'Permeability  k',
            description: 'PI ∝ k; time constant τ = V_p·c_t/PI ∝ 1/k. Higher permeability → faster decline. Both analytical and simulation update.',
            variants: [
                {
                    key: 'perm_tight',
                    label: 'k = 5 mD  (tight)',
                    description: 'Tight reservoir — low PI, slow decline, long-lived production.',
                    paramPatch: { uniformPermX: 5, uniformPermY: 5, uniformPermZ: 0.5 },
                    affectsAnalytical: true,
                },
                {
                    key: 'perm_base',
                    label: 'k = 20 mD  (base)',
                    description: 'Base Fetkovich permeability — matches the reference decline curve.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'perm_good',
                    label: 'k = 100 mD  (good)',
                    description: 'Good reservoir — high PI, rapid initial rate, steep exponential decline.',
                    paramPatch: { uniformPermX: 100, uniformPermY: 100, uniformPermZ: 10 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'timestep',
            label: 'Timestep  Δt',
            description: 'Timestep size modifies the numerical stability and accuracy of the simulation.',
            variants: [
                {
                    key: 'timestep_small',
                    label: 'Δt = 0.1 days  (small)',
                    description: 'Small timestep — higher accuracy, slower simulation.',
                    paramPatch: { delta_t_days: 0.1 },
                    affectsAnalytical: false,
                },
                {
                    key: 'timestep_large',
                    label: 'Δt = 1 days  (large)',
                    description: 'Large timestep — lower accuracy, faster simulation.',
                    paramPatch: { delta_t_days: 1 },
                    affectsAnalytical: false,
                },
                {
                    key: 'timestep_very_large',
                    label: 'Δt = 10 days  (very large)',
                    description: 'Very large timestep — lower accuracy, faster simulation.',
                    paramPatch: { delta_t_days: 10 },
                    affectsAnalytical: false,
                },
            ],
        },
    ],
};
