import { depletionLivePanels } from '../chartPanels/depletionLivePanels';
import type { Scenario } from '../scenarios';
import { depletionDef } from '../analyticalAdapters';

export const dep_pss: Scenario = {
    key: 'dep_pss',
    label: 'Pressure Depletion (Oil)',
    description: 'Bounded square depletion with a single producer. The simulator shows an early spatial drawdown transient before approaching the Dietz pseudo-steady-state tail, so this scenario is used for bounded-flow shape-factor checks plus numerical-resolution studies rather than aggressive PI scaling sweeps.',
    analyticalMethodSummary: 'Dietz pseudo-steady-state productivity-index model — predicts the late-time exponential rate and pressure decline for the active well location, skin, and storage terms once the bounded system is in PSS.',
    analyticalMethodReference: 'Dietz (1965); standard pseudo-steady-state productivity-index formulation.',
    chartLayoutKey: 'oil_depletion',
    defaultSensitivityDimensionKey: 'shape_factor',
    capabilities: {
        analyticalMethod: 'depletion',
        showSweepPanel: false,
        hasInjector: false,
        default3DScalar: null,
        requiresThreePhaseMode: false,
    },
    params: {
        // Fluid
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / rel perm
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 21×21×1 square drainage area, 420 m × 420 m × 10 m
        // Base: central producer (C_A ≈ 30.88)
        nx: 21,
        ny: 21,
        nz: 1,
        cellDx: 20,
        cellDy: 20,
        cellDz: 10,
        permMode: 'uniform',
        uniformPermX: 50,
        uniformPermY: 50,
        uniformPermZ: 5,
        // Initial conditions
        initialPressure: 300,
        initialSaturation: 0.1,
        // Wells: no injector — single producer
        injectorEnabled: false,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 100,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 10,
        producerJ: 10,
        well_radius: 0.1,
        well_skin: 0,
        // Numerics
        fimEnabled: false,
        delta_t_days: 0.1,
        steps: 160,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        gravityEnabled: false,
    },
    analyticalDef: depletionDef,
    liveChartPanels: depletionLivePanels,
    sensitivities: [
        {
            key: 'shape_factor',
            label: 'Well Location  (C_A)',
            description: 'Well position within a bounded square reservoir determines the Dietz shape factor C_A. Central well C_A ≈ 30.88 vs corner well C_A ≈ 0.56, which shifts the bounded-flow productivity index and the late-time decline constant. Both simulator and analytical update with well position.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'ca_center',
                    label: 'Centre  (C_A ≈ 30.88)',
                    description: 'Central producer — maximum drainage efficiency, slow decline. Base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'ca_corner',
                    label: 'Corner  (C_A ≈ 0.56)',
                    description: 'Corner producer — minimum drainage efficiency, fast decline.',
                    paramPatch: { producerI: 0, producerJ: 0 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'skin',
            label: 'Skin Factor  s',
            description: 'Skin modifies the near-wellbore pressure drop, scaling the productivity index and hence the bounded-flow decline rate. Positive skin = formation damage; negative skin = stimulation. — Hawkins (1956)',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'skin_neg',
                    label: 's = −1  (stimulated)',
                    description: 'Mild stimulation — higher PI and a faster late-time decline.',
                    paramPatch: { well_skin: -1 },
                    affectsAnalytical: true,
                },
                {
                    key: 'skin_zero',
                    label: 's = 0  (clean)',
                    description: 'No damage or stimulation — base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'skin_pos',
                    label: 's = +3  (damaged)',
                    description: 'Moderate formation damage — reduced PI and a slower late-time decline.',
                    paramPatch: { well_skin: 3 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'compressibility',
            label: 'Storage  c_t',
            description: 'Total compressibility c_t governs depletion storage. Higher c_t means more energy is stored in the bounded system, extending the decline time constant τ = V_p·c_t/PI. This is a clean analytical and simulation sensitivity.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'ct_low',
                    label: 'c_o = 5×10⁻⁶ bar⁻¹  (stiff)',
                    description: 'Lower fluid storage — faster bounded depletion and lower late-time support.',
                    paramPatch: { c_o: 5e-6 },
                    affectsAnalytical: true,
                },
                {
                    key: 'ct_base',
                    label: 'c_o = 1×10⁻⁵ bar⁻¹  (base)',
                    description: 'Base bounded-depletion storage case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'ct_high',
                    label: 'c_o = 2×10⁻⁵ bar⁻¹  (high storage)',
                    description: 'Higher fluid storage — slower bounded depletion and a longer visible decline tail.',
                    paramPatch: { c_o: 2e-5 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'timestep',
            label: 'Timestep  Δt',
            description: 'Timestep size controls how cleanly the transient-to-PSS transition is resolved. This axis is intentionally numerical: the analytical overlay is shared while the simulation demonstrates timestep sensitivity.',
            analyticalOverlayMode: 'shared',
            variants: [
                {
                    key: 'dt_fine',
                    label: 'Δt = 0.05 days  (fine)',
                    description: 'Fine timestep — best-resolved reference for the transient-to-PSS transition.',
                    paramPatch: { delta_t_days: 0.05, steps: 320 },
                    affectsAnalytical: false,
                },
                {
                    key: 'dt_base',
                    label: 'Δt = 0.1 days  (base)',
                    description: 'Base timestep chosen to resolve the depletion time constant while staying light enough for interactive use.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
                {
                    key: 'dt_coarse',
                    label: 'Δt = 0.25 days  (coarse)',
                    description: 'Coarser timestep — still usable, but it visibly compresses early depletion dynamics.',
                    paramPatch: { delta_t_days: 0.25, steps: 64 },
                    affectsAnalytical: false,
                },
            ],
        },
        {
            key: 'grid_refinement',
            label: 'Grid Refinement',
            description: 'Grid refinement tests whether the bounded depletion response is dominated by physical shape factor rather than cell-size and well-index discretisation effects. Geometry and reservoir size are preserved across variants.',
            analyticalOverlayMode: 'shared',
            variants: [
                {
                    key: 'grid_coarse',
                    label: '15×15 grid  (coarse)',
                    description: 'Coarser square grid with the same 420 m × 420 m footprint and centered producer.',
                    paramPatch: { nx: 15, ny: 15, cellDx: 28, cellDy: 28, producerI: 7, producerJ: 7 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_base',
                    label: '21×21 grid  (base)',
                    description: 'Base grid used for the bounded Dietz comparison.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_fine',
                    label: '35×35 grid  (fine)',
                    description: 'Finer square grid with the same reservoir dimensions and centered producer.',
                    paramPatch: { nx: 35, ny: 35, cellDx: 12, cellDy: 12, producerI: 17, producerJ: 17 },
                    affectsAnalytical: false,
                },
            ],
        },
    ],
};
