import { depletionLivePanels } from '../chartPanels/depletionLivePanels';
import type { Scenario } from '../scenarios';
import { depletionDef } from '../analyticalAdapters';

export const dep_decline: Scenario = {
    key: 'dep_decline',
    label: 'Finite-Reservoir Transition — Fetkovich',
    catalog: {
        group: 'depletion-decline',
        role: 'interpretation',
        caseMode: 'dep',
        parameterSummary: 'Finite constant-BHP slab · transient-to-boundary-dominated eigenfunction reference',
    },
    description: 'Constant-BHP production from a finite 1D reservoir. After the first three base timesteps—the Cartesian well block\'s startup response—the reference solves the distributed diffusion problem with a no-flow outer boundary and the same finite well productivity as a Robin boundary. Its eigenmodes cover spatial diffusion, boundary arrival, and the eventual single-mode exponential tail instead of imposing one tank exponential.',
    analyticalMethodSummary: 'Finite-slab eigenfunction solution with finite well productivity. Fetkovich boundary-dominated exponential decline appears as the asymptotic first mode, not as a full-history tank approximation.',
    analyticalMethodReference: 'Fetkovich (1980), SPE-4629-PA.',
    chartLayoutKey: 'fetkovich',
    defaultSensitivityDimensionKey: 'permeability',
    capabilities: {
        analyticalMethod: 'depletion',
        hasInjector: false,
        default3DScalar: 'pressure',
        requiresThreePhaseMode: false,
    },
    solverPolicy: {
        defaultSolver: 'impes',
        rationale: 'IMPES is the fast default for this constant-PVT decline case.',
    },
    params: {
        // Fluid
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / rel perm
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 1D slab 48 cells × 1 × 1, 480 m × 10 m × 10 m
        // High initial pressure + low BHP → drives exponential decline
        // Peaceman r_eq ≈ 1.98 m for 10×10 m cells; skin = -2 safe minimum
        // (ln(r_eq/r_w) ≈ 2.99; denominator = 2.99 + skin must remain > 0)
        nx: 48,
        ny: 1,
        nz: 1,
        cellDx: 10,
        cellDy: 10,
        cellDz: 10,
        permMode: 'uniform',
        uniformPermX: 20,
        uniformPermY: 20,
        uniformPermZ: 2,
        // Initial conditions: high pressure reservoir depleting to low BHP
        initialPressure: 1500,
        initialSaturation: 0.1,
        // Wells: single producer, no injector
        injectorEnabled: false,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 50,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 47,
        producerJ: 0,
        well_radius: 0.1,
        well_skin: 0,
        analyticalDepletionStartDays: 0.15,
        analyticalDepletionModel: 'finite-slab',
        // Numerics
        fimEnabled: false,
        delta_t_days: 0.05,
        steps: 480,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        gravityEnabled: false,
    },
    analyticalDef: depletionDef,
    liveChartPanels: depletionLivePanels,
    sensitivities: [
        {
            key: 'permeability',
            label: 'Permeability  k',
            description: 'Permeability changes both pressure diffusivity and well productivity, moving boundary arrival and the late-time eigenmode decline. The complete finite-domain reference updates for each variant.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'perm_tight',
                    label: 'k = 10 mD  (tight)',
                    description: 'Lower PI and longer time constant — slower boundary-dominated decline.',
                    paramPatch: { uniformPermX: 10, uniformPermY: 10, uniformPermZ: 1 },
                    affectsAnalytical: true,
                },
                {
                    key: 'perm_base',
                    label: 'k = 20 mD  (base)',
                    description: 'Base finite-slab case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'perm_good',
                    label: 'k = 40 mD  (good)',
                    description: 'Higher PI and shorter time constant — faster boundary-dominated decline without leaving the numerically well-resolved range.',
                    paramPatch: { uniformPermX: 40, uniformPermY: 40, uniformPermZ: 4 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'skin',
            label: 'Skin Factor  s',
            description: 'Skin changes the finite-productivity Robin boundary. It affects near-well drawdown and the eigenvalues without pretending the whole reservoir is a lumped tank.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'skin_neg',
                    label: 's = −1  (stimulated)',
                    description: 'Mild stimulation — higher PI and faster decline.',
                    paramPatch: { well_skin: -1 },
                    affectsAnalytical: true,
                },
                {
                    key: 'skin_zero',
                    label: 's = 0  (base)',
                    description: 'Base clean-well decline case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'skin_pos',
                    label: 's = +3  (damaged)',
                    description: 'Moderate damage — lower PI and slower decline.',
                    paramPatch: { well_skin: 3 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'timestep',
            label: 'Timestep  Δt',
            description: 'Timestep size changes how faithfully the early transient and late-time decline are resolved. The analytical overlay is shared because the reference curve itself is independent of the numerical timestep.',
            analyticalOverlayMode: 'shared',
            variants: [
                {
                    key: 'timestep_small',
                    label: 'Δt = 0.025 days  (fine)',
                    description: 'Fine timestep — best-resolved transition curve.',
                    paramPatch: { delta_t_days: 0.025, steps: 960 },
                    affectsAnalytical: false,
                },
                {
                    key: 'timestep_base',
                    label: 'Δt = 0.05 days  (base)',
                    description: 'Base timestep resolves boundary arrival and the decline tail.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
                {
                    key: 'timestep_large',
                    label: 'Δt = 0.1 days  (coarse)',
                    description: 'Coarse diagnostic rung; visible separation is numerical damping, not different reservoir physics.',
                    paramPatch: { delta_t_days: 0.1, steps: 240 },
                    affectsAnalytical: false,
                },
            ],
        },
        {
            key: 'grid_refinement',
            label: 'Grid Refinement',
            description: '1D grid refinement isolates well-index and spatial discretisation effects while preserving the same 480 m slab and end-well geometry.',
            analyticalOverlayMode: 'shared',
            variants: [
                {
                    key: 'grid_coarse',
                    label: '24 cells  (coarse)',
                    description: 'Coarser 1D slab with the same total length and end-well placement.',
                    paramPatch: { nx: 24, cellDx: 20, producerI: 23 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_base',
                    label: '48 cells  (base)',
                    description: 'Base 1D Fetkovich decline grid.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_fine',
                    label: '96 cells  (fine)',
                    description: 'Finer 1D slab with the same total length and end-well placement.',
                    paramPatch: { nx: 96, cellDx: 5, producerI: 95 },
                    affectsAnalytical: false,
                },
            ],
        },
    ],
};
