import type { Scenario } from '../scenarios';

export const dep_pss: Scenario = {
    key: 'dep_pss',
    label: 'Pressure Depletion (Oil)',
    description: 'Bounded square reservoir under pseudo-steady-state. Well position sets the Dietz shape factor C_A (centre C_A ≈ 30.88 vs corner C_A ≈ 0.56), controlling the rate of pressure decline.',
    analyticalMethodSummary: 'PSS productivity-index model — predicts exponential rate and pressure decline for the active well location, skin, and permeability.',
    analyticalMethodReference: 'Dietz (1965); standard pseudo-steady-state productivity-index formulation.',
    scenarioClass: 'depletion',
    domain: 'depletion',
    chartPreset: 'oil_depletion',
    defaultSensitivityDimensionKey: 'shape_factor',
    capabilities: {
        analyticalMethod: 'depletion',
        showSweepPanel: false,
        hasInjector: false,
        default3DScalar: null,
        requiresThreePhaseMode: false,
    },
    params: {
        analyticalSolutionMode: 'depletion',
        // Fluid
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / rel perm
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 21×21×1 square drainage area, 420 m × 420 m × 10 m
        // Base: central producer (C_A ≈ 30.88)
        nx: 21,
        ny: 21,
        nz: 1,
        cellDx: 20,
        cellDy: 20,
        cellDz: 10,
        permMode: 'uniform',
        uniformPermX: 50,
        uniformPermY: 50,
        uniformPermZ: 5,
        // Initial conditions
        initialPressure: 300,
        initialSaturation: 0.1,
        // Wells: no injector — single producer
        injectorEnabled: false,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 100,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 10,
        producerJ: 10,
        well_radius: 0.1,
        well_skin: 0,
        // Numerics
        delta_t_days: 1,
        steps: 50,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        gravityEnabled: false,
    },
    sensitivities: [
        {
            key: 'shape_factor',
            label: 'Well Location  (C_A)',
            description: 'Well position within a bounded square reservoir determines the Dietz shape factor C_A. Central well C_A ≈ 30.88 vs corner well C_A ≈ 0.56 — a ~55× difference that dramatically changes decline rate. Both simulator and analytical update with well position.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'ca_center',
                    label: 'Centre  (C_A ≈ 30.88)',
                    description: 'Central producer — maximum drainage efficiency, slow decline. Base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'ca_corner',
                    label: 'Corner  (C_A ≈ 0.56)',
                    description: 'Corner producer — minimum drainage efficiency, fast decline.',
                    paramPatch: { producerI: 0, producerJ: 0 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'skin',
            label: 'Skin Factor  s',
            description: 'Skin modifies the near-wellbore pressure drop, scaling the productivity index and hence the decline rate. Positive skin = formation damage; negative skin = stimulation. — Hawkins (1956)',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'skin_neg',
                    label: 's = −2  (stimulated)',
                    description: 'Mild stimulation (e.g. acid job) — higher PI, faster decline.',
                    paramPatch: { well_skin: -2 },
                    affectsAnalytical: true,
                },
                {
                    key: 'skin_zero',
                    label: 's = 0  (clean)',
                    description: 'No damage or stimulation — base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'skin_pos',
                    label: 's = +5  (damaged)',
                    description: 'Moderate formation damage (fines, mud filtrate) — reduced PI, slower decline.',
                    paramPatch: { well_skin: 5 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'permeability',
            label: 'Permeability  k',
            description: 'PI ∝ k; decline time constant τ = V_p·c_t/PI is inversely proportional to k. Higher permeability → faster, steeper decline. Both analytical and simulation update.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'perm_tight',
                    label: 'k = 10 mD  (tight)',
                    description: 'Tight reservoir — low PI, slow decline, long-lived production.',
                    paramPatch: { uniformPermX: 10, uniformPermY: 10, uniformPermZ: 1 },
                    affectsAnalytical: true,
                },
                {
                    key: 'perm_base',
                    label: 'k = 50 mD  (base)',
                    description: 'Base Dietz permeability.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'perm_good',
                    label: 'k = 200 mD  (good)',
                    description: 'Good reservoir — high PI, rapid initial rate, steep decline.',
                    paramPatch: { uniformPermX: 200, uniformPermY: 200, uniformPermZ: 20 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'compressibility',
            label: 'Compressibility  c_o',
            description: 'Total compressibility c_t governs reservoir storage. Higher c_t → more energy stored → longer decline. τ = V_p·c_t/PI. — Craft & Hawkins (1959)',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'ct_low',
                    label: 'c_o = 5×10⁻⁶ bar⁻¹  (stiff)',
                    description: 'Stiff undersaturated oil — low storage, fast decline.',
                    paramPatch: { c_o: 5e-6 },
                    affectsAnalytical: true,
                },
                {
                    key: 'ct_base',
                    label: 'c_o = 1×10⁻⁵ bar⁻¹  (base)',
                    description: 'Typical black-oil compressibility — base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'ct_high',
                    label: 'c_o = 5×10⁻⁵ bar⁻¹  (volatile)',
                    description: 'High compressibility (near bubble point or volatile oil) — large energy storage, extended decline.',
                    paramPatch: { c_o: 5e-5 },
                    affectsAnalytical: true,
                },
            ],
        },
    ],
};
