import type { Scenario } from '../scenarios';

export const gas_injection: Scenario = {
    key: 'gas_injection',
    label: 'Gas Injection',
    description: 'Gas injector displacing oil in a 1D homogeneous reservoir; no initial free gas. The numerical gas front sharpens toward the analytical solution as grid resolution increases.',
    analyticalMethodSummary: 'Fractional-flow solution with Welge shock construction for gas-oil displacement — predicts gas breakthrough timing and post-breakthrough recovery.',
    analyticalMethodReference: 'Buckley and Leverett (1942); Welge (1952) — applied to gas-oil system.',
    scenarioClass: 'gas-oil-bl',
    domain: 'gas',
    chartPreset: 'gas_oil_bl',
    defaultSensitivityDimensionKey: 'mobility',
    capabilities: {
        analyticalMethod: 'gas-oil-bl',
        primaryRateCurve: 'gas-cut',
        showSweepPanel: false,
        analyticalNativeXAxis: 'pvi',
        hasTauDimensionlessTime: false,
        hasInjector: true,
        default3DScalar: 'saturation_gas',
        requiresThreePhaseMode: true,
    },
    params: {
        analyticalSolutionMode: 'waterflood',
        nx: 50, ny: 1, nz: 1,
        cellDx: 20, cellDy: 50, cellDz: 10,
        initialPressure: 250,
        initialSaturation: 0.2,
        initialGasSaturation: 0,
        reservoirPorosity: 0.2,
        uniformPermX: 100, uniformPermY: 100, uniformPermZ: 10,
        permMode: 'uniform',
        s_wc: 0.2, s_or: 0.15,
        s_gc: 0.05, s_gr: 0.05, s_org: 0.20,
        n_w: 2.0, n_o: 2.0, n_g: 1.5,
        k_rw_max: 0.4, k_ro_max: 1.0, k_rg_max: 0.8,
        mu_w: 0.5, mu_o: 2.0, mu_g: 0.02,
        c_w: 3e-6, c_o: 1e-5, c_g: 1e-4,
        rho_w: 1000, rho_o: 800, rho_g: 10,
        depth_reference: 0,
        volume_expansion_o: 1.0, volume_expansion_w: 1.0,
        rock_compressibility: 1e-6,
        injectorEnabled: true,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 350, producerBhp: 100,
        injectorI: 0, injectorJ: 0,
        producerI: 49, producerJ: 0,
        well_radius: 0.1, well_skin: 0,
        capillaryEnabled: false,
        capillaryPEntry: 0, capillaryLambda: 2,
        gravityEnabled: false,
        threePhaseModeEnabled: true,
        injectedFluid: 'gas',
        pcogEnabled: false, pcogPEntry: 3, pcogLambda: 2,
        delta_t_days: 2,
        steps: 150,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
    },
    sensitivities: [
        {
            key: 'mobility',
            label: 'Gas Mobility Ratio',
            description: 'Vary gas viscosity to explore how the gas-oil mobility ratio M = (k_rg/μ_g)/(k_ro/μ_o) controls gas breakthrough timing and oil recovery. Gas is typically much more mobile than oil (very low μ_g), giving strongly unfavorable M.',
            variants: [
                {
                    key: 'mob_favorable',
                    label: 'M ≈ 4  (μ_g = 0.1 cp)',
                    description: 'Relatively favorable gas mobility — later breakthrough, better recovery. Unusual for gas but instructive.',
                    paramPatch: { mu_g: 0.1 },
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_base',
                    label: 'M ≈ 40  (μ_g = 0.02 cp)',
                    description: 'Base case — typical gas viscosity, strongly unfavorable mobility. Early gas breakthrough.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_adverse',
                    label: 'M ≈ 200  (μ_g = 0.005 cp)',
                    description: 'Extremely adverse mobility — very early breakthrough, poor recovery. Typical of light gas in heavy oil.',
                    paramPatch: { mu_g: 0.005 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 's_gc',
            label: 'Critical Gas Saturation S_gc',
            description: 'S_gc is the minimum gas saturation for gas to flow. Higher S_gc delays gas breakthrough but traps more gas behind the front.',
            variants: [
                {
                    key: 'sgc_low',
                    label: 'S_gc = 0.02',
                    description: 'Low critical gas — gas flows at very low saturations.',
                    paramPatch: { s_gc: 0.02 },
                    affectsAnalytical: true,
                },
                {
                    key: 'sgc_base',
                    label: 'S_gc = 0.05  (base)',
                    description: 'Moderate critical gas saturation — base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'sgc_high',
                    label: 'S_gc = 0.10',
                    description: 'High critical gas saturation — delays gas flow onset.',
                    paramPatch: { s_gc: 0.10 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'perm',
            label: 'Permeability',
            description: 'Permeability controls total flow rate (both phases), affecting how quickly the displacement front reaches the producer. The analytical BL solution is permeability-independent on a PVI basis.',
            variants: [
                {
                    key: 'perm_low',
                    label: 'k = 10 mD  (tight)',
                    description: 'Low permeability — slower displacement, same BL profile on PVI axis.',
                    paramPatch: { uniformPermX: 10, uniformPermY: 10, uniformPermZ: 1 },
                    affectsAnalytical: false,
                },
                {
                    key: 'perm_base',
                    label: 'k = 100 mD  (base)',
                    description: 'Base permeability.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
                {
                    key: 'perm_high',
                    label: 'k = 1000 mD  (high)',
                    description: 'High permeability — faster displacement, more throughput per timestep.',
                    paramPatch: { uniformPermX: 1000, uniformPermY: 1000, uniformPermZ: 100 },
                    affectsAnalytical: false,
                },
            ],
        },
        {
            key: 'grid',
            label: 'Grid Resolution',
            description: 'Numerical convergence study. The gas-oil BL analytical solution is grid-independent — only the simulation changes as the grid is refined.',
            chartPresetOverride: 'gas_oil_bl',
            variants: [
                {
                    key: 'grid_10',
                    label: '10 cells  (coarse)',
                    description: 'Coarse 10-cell grid — large numerical diffusion, smeared gas front.',
                    paramPatch: { nx: 10, producerI: 9, cellDx: 100 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_25',
                    label: '25 cells  (medium)',
                    description: 'Medium grid — moderate numerical diffusion.',
                    paramPatch: { nx: 25, producerI: 24, cellDx: 40 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_50',
                    label: '50 cells  (base)',
                    description: 'Base 50-cell grid.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_100',
                    label: '100 cells  (fine)',
                    description: 'Fine 100-cell grid — sharper gas front.',
                    paramPatch: { nx: 100, producerI: 99, cellDx: 10 },
                    affectsAnalytical: false,
                },
            ],
        },
    ],
};
