import type { Scenario } from '../scenarios';

export const sweep_areal: Scenario = {
    key: 'sweep_areal',
    label: 'Areal Sweep (XY)',
    description: 'Five-spot pattern flood in 2D (XY). Areal sweep E_A at breakthrough is strongly controlled by end-point mobility ratio: E_A(BT) ≈ 0.70 at M = 1, dropping sharply for unfavourable M > 1.',
    analyticalMethodSummary: 'Craig five-spot correlation — predicts E_A vs PVI for a homogeneous pattern. Heterogeneous variants show the additional sweep penalty on top of this baseline.',
    analyticalMethodReference: 'Craig (1971); Dyes, Caudle, and Erickson (1954).',
    scenarioClass: 'waterflood',
    domain: 'sweep',
    chartPreset: 'sweep',
    defaultSensitivityDimensionKey: 'mobility',
    capabilities: {
        analyticalMethod: 'buckley-leverett',
        showSweepPanel: true,
        hasInjector: true,
        default3DScalar: 'saturation_water',
        requiresThreePhaseMode: false,
    },
    params: {
        analyticalSolutionMode: 'waterflood',
        // Fluid
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / rel perm
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 21×21×1 five-spot, 420 m × 420 m × 10 m
        nx: 21,
        ny: 21,
        nz: 1,
        cellDx: 20,
        cellDy: 20,
        cellDz: 10,
        permMode: 'uniform',
        uniformPermX: 200,
        uniformPermY: 200,
        uniformPermZ: 20,
        // Initial conditions
        initialPressure: 300,
        initialSaturation: 0.1,
        // Wells: injector at origin, producer at far corner
        injectorEnabled: true,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 100,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 20,
        producerJ: 20,
        well_radius: 0.1,
        well_skin: 0,
        // Numerics
        delta_t_days: 0.5,
        steps: 120,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        gravityEnabled: false,
    },
    sensitivities: [
        {
            key: 'mobility',
            label: 'Mobility Ratio',
            description: 'End-point mobility ratio M = (k_rw_max/μ_w)/(k_ro_max/μ_o) is the primary control on five-spot areal sweep efficiency. Both simulation and analytical (Craig polynomial) update.',
            variants: [
                {
                    key: 'mob_favorable',
                    label: 'M ≈ 0.5  (μ_o = 0.25 cp)',
                    description: 'Favourable mobility — high areal sweep, late breakthrough, piston-like.',
                    paramPatch: { mu_o: 0.25 },
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_unit',
                    label: 'M ≈ 2  (μ_o = 1.0 cp)',
                    description: 'Moderate mobility ratio — base case. E_A(BT) ≈ 0.58.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_unfavorable',
                    label: 'M ≈ 10  (μ_o = 5.0 cp)',
                    description: 'Strongly unfavourable — viscous channelling, early breakthrough, poor areal sweep.',
                    paramPatch: { mu_o: 5.0 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'areal_heterogeneity',
            label: 'Areal Heterogeneity',
            description: 'Introduce seeded within-layer permeability variation to test areal sweep sensitivity beyond the Craig five-spot correlation. Simulation changes, while the analytical areal sweep curve remains shared context because the current model does not resolve within-layer randomness.',
            variants: [
                {
                    key: 'areal_uniform',
                    label: 'Uniform  (baseline pattern)',
                    description: 'Uniform permeability in the XY plane — clean Craig-style five-spot baseline.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
                {
                    key: 'areal_mild_random',
                    label: 'Mild random  (seeded)',
                    description: 'Moderate within-layer permeability variation — mild channelling and pattern distortion.',
                    paramPatch: {
                        permMode: 'random',
                        minPerm: 120,
                        maxPerm: 280,
                        useRandomSeed: true,
                        randomSeed: 4201,
                    },
                    affectsAnalytical: false,
                },
                {
                    key: 'areal_strong_random',
                    label: 'Strong random  (seeded)',
                    description: 'Strong within-layer variation — pronounced areal bypassing and early preferential flow paths.',
                    paramPatch: {
                        permMode: 'random',
                        minPerm: 40,
                        maxPerm: 500,
                        useRandomSeed: true,
                        randomSeed: 4202,
                    },
                    affectsAnalytical: false,
                },
            ],
        },
        {
            key: 'sor',
            label: 'Residual Oil  S_or',
            description: 'S_or affects the endpoint mobility ratio (k_ro endpoint shifts with S_or), influencing both displacement efficiency and areal sweep. Both simulation and analytical update.',
            variants: [
                {
                    key: 'sor_low',
                    label: 'S_or = 0.05',
                    description: 'Very low trapping — nearly complete displacement, high recovery ceiling.',
                    paramPatch: { s_or: 0.05 },
                    affectsAnalytical: true,
                },
                {
                    key: 'sor_base',
                    label: 'S_or = 0.10  (base)',
                    description: 'Moderate residual — standard endpoint.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'sor_high',
                    label: 'S_or = 0.25',
                    description: 'High trapping — tight carbonate-like, reduced displacement efficiency.',
                    paramPatch: { s_or: 0.25 },
                    affectsAnalytical: true,
                },
            ],
        },
    ],
};
