import type { Scenario } from '../scenarios';

export const sweep_combined: Scenario = {
    key: 'sweep_combined',
    label: 'Combined Sweep (3D)',
    description: 'Volumetric sweep E_vol = E_A × E_V in a 3D five-spot-over-layers flood. Two axes: a 2×2 interaction matrix of mobility vs. layering, and a progressive sweep from ideal to fully-degraded conditions.',
    analyticalMethodSummary: 'Stiles layer-by-layer sweep: the total RF and combined E_vol use layer-by-layer Buckley-Leverett displacement inside the Craig-contacted region, while E_A and E_V remain analytical diagnostic decomposition views.',
    analyticalMethodReference: 'Stiles (1949); Craig (1971); Buckley and Leverett (1942); Welge (1952).',
    analyticalOptions: [
        {
            key: 'stiles',
            label: 'Stiles',
            summary: 'Stiles layer-by-layer sweep: the total RF and combined E_vol use layer-by-layer Buckley-Leverett displacement inside the Craig-contacted region, while E_A and E_V remain analytical diagnostic decomposition views.',
            reference: 'Stiles (1949); Craig (1971); Buckley and Leverett (1942); Welge (1952).',
            sweepMethod: 'stiles',
            default: true,
        },
        {
            key: 'dykstra',
            label: 'Dykstra-Parsons',
            summary: 'Factorized sweep model: the total RF and combined E_vol come from Craig areal × Dykstra-Parsons vertical × BL displacement through the local-PVI approximation, while E_A and E_V remain analytical diagnostic decomposition views.',
            reference: 'Craig (1971); Dykstra and Parsons (1950); Buckley and Leverett (1942); Welge (1952).',
            sweepMethod: 'dykstra-parsons',
        },
    ],
    scenarioClass: 'waterflood',
    domain: 'sweep',
    chartPreset: 'sweep',
    defaultSensitivityDimensionKey: 'interaction_core',
    capabilities: {
        analyticalMethod: 'buckley-leverett',
        showSweepPanel: true,
        sweepGeometry: 'both',
        hasInjector: true,
        default3DScalar: 'saturation_water',
        requiresThreePhaseMode: false,
    },
    params: {
        analyticalSolutionMode: 'waterflood',
        // Fluid
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / rel perm
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 21×21×5 five-spot + 5 layers, 420 m × 420 m × 20 m
        // Base: moderate heterogeneity (V_DP ≈ 0.5) + moderate mobility (M ≈ 2)
        nx: 21,
        ny: 21,
        nz: 5,
        cellDx: 20,
        cellDy: 20,
        cellDz: 4,
        permMode: 'perLayer',
        uniformPermX: 100,
        uniformPermY: 100,
        uniformPermZ: 10,
        layerPermsX: [200, 150, 100, 60, 40],
        layerPermsY: [200, 150, 100, 60, 40],
        layerPermsZ: [20, 15, 10, 6, 4],
        // Initial conditions
        initialPressure: 300,
        initialSaturation: 0.1,
        // Wells
        injectorEnabled: true,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 100,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 20,
        producerJ: 20,
        well_radius: 0.1,
        well_skin: 0,
        // Numerics
        delta_t_days: 0.25,
        steps: 1500,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        gravityEnabled: false,
    },
    sensitivities: [
        {
            key: 'interaction_core',
            label: 'Mobility × Vertical Heterogeneity',
            description: 'Minimal 2 × 2 interaction map for 3D sweep. Separate mobility-only, layering-only, and compounded penalties without introducing areal randomness.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'interaction_favorable_uniform',
                    label: 'Favorable + uniform',
                    description: 'Near-piston 3D baseline: favorable mobility and no vertical heterogeneity.',
                    paramPatch: {
                        mu_o: 0.5,
                        permMode: 'uniform',
                        uniformPermX: 100,
                        uniformPermY: 100,
                        uniformPermZ: 10,
                    },
                    affectsAnalytical: true,
                },
                {
                    key: 'interaction_unfavorable_uniform',
                    label: 'Unfavorable + uniform',
                    description: 'Mobility penalty only: poor mobility with otherwise uniform layering.',
                    paramPatch: {
                        mu_o: 5.0,
                        permMode: 'uniform',
                        uniformPermX: 100,
                        uniformPermY: 100,
                        uniformPermZ: 10,
                    },
                    affectsAnalytical: true,
                },
                {
                    key: 'interaction_favorable_layered',
                    label: 'Favorable + layered',
                    description: 'Vertical heterogeneity penalty only: good mobility in a layered reservoir.',
                    paramPatch: { mu_o: 0.5 },
                    affectsAnalytical: true,
                },
                {
                    key: 'interaction_unfavorable_layered',
                    label: 'Unfavorable + layered',
                    description: 'Compounded mobility plus vertical layering penalty in the same 3D flood.',
                    paramPatch: { mu_o: 5.0 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'sweep_ladder',
            label: 'Ideal to Worst',
            description: 'Progressive sweep comparison from ideal to fully degraded: starts with uniform permeability and favorable mobility, then adds vertical heterogeneity, full-field randomness, and finally unfavorable mobility. Random-heterogeneity variants are simulation-focused; the analytical sweep curve remains shared context.',
            analyticalOverlayMode: 'shared',
            variants: [
                {
                    key: 'ladder_ideal',
                    label: 'Ideal  (uniform, favorable)',
                    description: 'Best-case 3D sweep: uniform permeability and favorable mobility.',
                    paramPatch: {
                        mu_o: 0.5,
                        permMode: 'uniform',
                        uniformPermX: 100,
                        uniformPermY: 100,
                        uniformPermZ: 10,
                    },
                    affectsAnalytical: false,
                },
                {
                    key: 'ladder_vertical',
                    label: 'Vertical only  (layered, favorable)',
                    description: 'First degradation step: layered vertical heterogeneity with favorable mobility retained.',
                    paramPatch: { mu_o: 0.5 },
                    affectsAnalytical: false,
                },
                {
                    key: 'ladder_full_het',
                    label: 'Vertical + areal heterogeneity',
                    description: 'Seeded full-field random permeability to approximate simultaneous areal and vertical non-uniformity at moderate mobility.',
                    paramPatch: {
                        permMode: 'random',
                        minPerm: 40,
                        maxPerm: 500,
                        useRandomSeed: true,
                        randomSeed: 4301,
                    },
                    affectsAnalytical: false,
                },
                {
                    key: 'ladder_worst',
                    label: 'Worst case  (full heterogeneity, unfavorable)',
                    description: 'Fully degraded: full-field heterogeneity combined with strongly unfavorable mobility.',
                    paramPatch: {
                        mu_o: 5.0,
                        permMode: 'random',
                        minPerm: 20,
                        maxPerm: 700,
                        useRandomSeed: true,
                        randomSeed: 4302,
                    },
                    affectsAnalytical: false,
                },
            ],
        },
    ],
};
