import type { Scenario } from '../scenarios';
import { waterfloodBLDef } from '../analyticalAdapters';

export const wf_bl1d: Scenario = {
    key: 'wf_bl1d',
    label: '1D Waterflood',
    catalog: {
        group: 'buckley-leverett-displacement',
        role: 'simulation',
        caseMode: 'wf',
        parameterSummary: '1D oil–water displacement · homogeneous rock · Buckley–Leverett + Welge reference',
    },
    description: 'Viscous-dominated 1D displacement — no gravity or capillary pressure. The numerical shock front sharpens toward the analytical solution as grid resolution increases. Because the Buckley-Leverett reference is independent of both grid and timestep, this case also carries the catalog\'s FIM-vs-IMPES comparison: the two formulations are judged against a fixed analytical solution rather than only against each other.',
    analyticalMethodSummary: 'Fractional-flow solution with Welge shock construction — predicts breakthrough timing and post-breakthrough recovery, independent of grid resolution.',
    analyticalMethodReference: 'Buckley and Leverett (1942); Welge (1952).',
    chartLayoutKey: 'waterflood',
    chartLayoutPatch: {
        chart: {
            panels: {
                oil_rate: {
                    suppressLeadingOutliers: { medianRatio: 2, maxLeadingFraction: 0.1 },
                },
            },
        },
    },
    defaultSensitivityDimensionKey: 'mobility',
    capabilities: {
        analyticalMethod: 'buckley-leverett',
        hasInjector: true,
        default3DScalar: 'saturation_water',
        requiresThreePhaseMode: false,
    },
    solverPolicy: {
        defaultSolver: 'impes',
        rationale: 'IMPES is the fast, validated default for this oil/water displacement.',
    },
    params: {
        // Fluid properties
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / relative permeability
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        // Capillary pressure (off by default)
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 96-cell 1D slab, 960 m total length
        nx: 96,
        ny: 1,
        nz: 1,
        cellDx: 10,
        cellDy: 10,
        cellDz: 1,
        permMode: 'uniform',
        uniformPermX: 2000,
        uniformPermY: 2000,
        uniformPermZ: 200,
        // Initial conditions
        initialPressure: 300,
        initialSaturation: 0.1,
        // Wells: pressure-controlled injector + producer
        injectorEnabled: true,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 100,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 95,
        producerJ: 0,
        well_radius: 0.1,
        well_skin: 0,
        // Numerics
        fimEnabled: false,
        delta_t_days: 0.25,
        steps: 200,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        // Physics toggles
        gravityEnabled: false,
    },
    analyticalDef: waterfloodBLDef,
    sensitivities: [
        {
            key: 'mobility',
            label: 'Mobility Ratio',
            description: 'Vary oil viscosity to explore how the end-point mobility ratio M = (k_rw/μ_w)/(k_ro/μ_o) controls breakthrough timing, watercut shape, and recovery. Both simulation and analytical solution update.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'mob_favorable',
                    label: 'M ≈ 1  (μ_o = 0.5 cp)',
                    description: 'Near-unit mobility ratio — sharp, piston-like displacement. Best waterflood recovery.',
                    paramPatch: { mu_o: 0.5 },
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_base',
                    label: 'M ≈ 2  (μ_o = 1.0 cp)',
                    description: 'Base case — moderate unfavourable mobility. BL shock at S_w ≈ 0.55.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_case_b',
                    label: 'M ≈ 2.3  and tighter rock (Case B)',
                    description: 'BL Case B — adverse mobility with tighter rock (μ_o=1.4, μ_w=0.6, n_w=2.2, s_wc=s_or=0.15). Earlier breakthrough than base.',
                    paramPatch: { mu_w: 0.6, mu_o: 1.4, initialSaturation: 0.15, s_wc: 0.15, s_or: 0.15, n_w: 2.2 },
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_unfavorable',
                    label: 'M ≈ 10  (μ_o = 5.0 cp)',
                    description: 'Strongly unfavourable — very early breakthrough relative to injected volume (PVI), poor recovery. Classic viscous fingering regime.',
                    paramPatch: { mu_o: 5.0, steps: 300 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'corey_no',
            label: 'Corey Exponent n_o',
            description: 'The Corey exponent controls the curvature of k_ro(S_w). Higher n_o → more convex k_ro → oil transmits less readily at intermediate saturations. Both simulation and analytical update.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'no_15',
                    label: 'n_o = 1.5  (near-linear)',
                    description: 'Near-linear k_ro — oil transmits readily at intermediate saturations, slower BL shock.',
                    paramPatch: { n_o: 1.5 },
                    affectsAnalytical: true,
                },
                {
                    key: 'no_20',
                    label: 'n_o = 2.0  (base)',
                    description: 'Standard Corey exponent — base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'no_35',
                    label: 'n_o = 3.5  (convex)',
                    description: 'Strongly convex k_ro — oil permeability collapses quickly near residual, earlier breakthrough.',
                    paramPatch: { n_o: 3.5 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'sor',
            label: 'Residual Oil  S_or',
            description: 'S_or sets the ceiling on waterflood recovery: RF_max = (1 − S_wc − S_or)/(1 − S_wc). Also shifts the fractional flow curve endpoint. Both simulation and analytical update.',
            analyticalOverlayMode: 'per-result',
            variants: [
                {
                    key: 'sor_low',
                    label: 'S_or = 0.05  (low trapping)',
                    description: 'Low residual trapping — high recovery ceiling, typical of clean sandstone.',
                    paramPatch: { s_or: 0.05 },
                    affectsAnalytical: true,
                },
                {
                    key: 'sor_mid',
                    label: 'S_or = 0.15  (base)',
                    description: 'Moderate residual oil — base case.',
                    paramPatch: { s_or: 0.15 },
                    affectsAnalytical: true,
                },
                {
                    key: 'sor_high',
                    label: 'S_or = 0.30  (high trapping)',
                    description: 'High residual trapping — poor recovery ceiling, typical of carbonates or tight rock.',
                    paramPatch: { s_or: 0.30 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'grid',
            label: 'Grid Resolution',
            description: 'Numerical convergence study. The Buckley-Leverett analytical solution is grid-independent — only the simulation changes as the grid is refined.',
            analyticalOverlayMode: 'shared',
            chartLayoutKeyOverride: 'waterflood',
            variants: [
                {
                    key: 'grid_3',
                    label: '3 cells  (coarse)',
                    description: 'Coarse 3-cell grid — large numerical diffusion, smeared front.',
                    paramPatch: { nx: 3, producerI: 2, cellDx: 320 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_6',
                    label: '6 cells  (coarse)',
                    description: 'Coarse 6-cell grid — large numerical diffusion, smeared front.',
                    paramPatch: { nx: 6, producerI: 5, cellDx: 160 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_24',
                    label: '24 cells  (coarse)',
                    description: 'Coarse 24-cell grid — large numerical diffusion, smeared front.',
                    paramPatch: { nx: 24, producerI: 23, cellDx: 40 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_96',
                    label: '96 cells  (fine)',
                    description: 'Fine 96-cell reference grid — matches the base case exactly.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
            ],
        },
        {
            key: 'solver_formulation',
            label: 'Solver (FIM vs IMPES)',
            description: 'Solve the identical displacement two ways — implicit pressure with explicit saturation transport (IMPES), or one coupled nonlinear Newton solve (FIM) — with everything else held fixed. The Buckley-Leverett reference is independent of both grid and timestep, so it stays put while the numerical trajectories move: their separation is numerical error rather than different physics. At the fine 0.25-day report step, IMPES and FIM agree to 0.12% in cumulative oil over the 50-day flood (1362.4 vs 1364.1 m³). Coarsening the requested report step to 5 days leaves IMPES effectively unchanged (1362.5 m³) because its stability control still selects smaller internal substeps, while FIM finishes 1.0% below its fine-step result (1350.6 m³). FIM also fragments each requested step through its nonlinear timestep controller, so this comparison teaches how formulation and internal step selection interact — not that the requested report step is the step each solver actually takes.',
            analyticalOverlayMode: 'shared',
            variesSolver: true,
            variants: [
                {
                    key: 'solver_impes_base',
                    label: 'IMPES 0.25-day steps (base)',
                    description: 'The scenario default: implicit pressure followed by explicit saturation transport, with stability-driven internal subdivision.',
                    paramPatch: { },
                    affectsAnalytical: false,
                },
                {
                    key: 'solver_fim_base',
                    label: 'FIM 0.25-day steps',
                    description: 'Fully implicit coupled pressure/saturation Newton solve at the same fine report step. Its cumulative oil agrees with IMPES to 0.12% over the 50-day flood.',
                    paramPatch: { fimEnabled: true },
                    affectsAnalytical: false,
                },
                {
                    key: 'solver_impes_coarse',
                    label: 'IMPES 5-day steps',
                    description: 'A coarse requested report step, but stability-driven internal subdivision leaves the IMPES result effectively unchanged from the fine-step run.',
                    paramPatch: { delta_t_days: 5, steps: 10,},
                    affectsAnalytical: false,
                },
                {
                    key: 'solver_fim_coarse',
                    label: 'FIM 5-day steps',
                    description: 'A coarse requested report step that the nonlinear controller fragments internally; cumulative oil finishes 1.0% below the fine-step FIM run.',
                    paramPatch: { fimEnabled: true, delta_t_days: 5, steps: 10 },
                    affectsAnalytical: false,
                },
            ],
        },
    ],
};
