import type { Scenario } from '../scenarios';

export const wf_bl1d: Scenario = {
    key: 'wf_bl1d',
    label: '1D Waterflood',
    description: 'Viscous-dominated 1D displacement — no gravity or capillary pressure. The numerical shock front sharpens toward the analytical solution as grid resolution increases.',
    analyticalMethodSummary: 'Fractional-flow solution with Welge shock construction — predicts breakthrough timing and post-breakthrough recovery, independent of grid resolution.',
    analyticalMethodReference: 'Buckley and Leverett (1942); Welge (1952).',
    scenarioClass: 'waterflood',
    domain: 'waterflood',
    chartPreset: 'waterflood',
    defaultSensitivityDimensionKey: 'mobility',
    capabilities: {
        analyticalMethod: 'buckley-leverett',
        showSweepPanel: false,
        hasInjector: true,
        default3DScalar: 'saturation_water',
        requiresThreePhaseMode: false,
    },
    params: {
        analyticalSolutionMode: 'waterflood',
        // Fluid properties
        mu_w: 0.5,
        mu_o: 1.0,
        c_o: 1e-5,
        c_w: 3e-6,
        rock_compressibility: 1e-6,
        depth_reference: 0,
        volume_expansion_o: 1,
        volume_expansion_w: 1,
        rho_w: 1000,
        rho_o: 800,
        // Rock / relative permeability
        reservoirPorosity: 0.2,
        s_wc: 0.1,
        s_or: 0.1,
        n_w: 2,
        n_o: 2,
        k_rw_max: 1,
        k_ro_max: 1,
        // Capillary pressure (off by default)
        capillaryEnabled: false,
        capillaryPEntry: 0,
        capillaryLambda: 2,
        // Grid: 96-cell 1D slab, 960 m total length
        nx: 96,
        ny: 1,
        nz: 1,
        cellDx: 10,
        cellDy: 10,
        cellDz: 1,
        permMode: 'uniform',
        uniformPermX: 2000,
        uniformPermY: 2000,
        uniformPermZ: 200,
        // Initial conditions
        initialPressure: 300,
        initialSaturation: 0.1,
        // Wells: pressure-controlled injector + producer
        injectorEnabled: true,
        injectorControlMode: 'pressure',
        producerControlMode: 'pressure',
        injectorBhp: 500,
        producerBhp: 100,
        targetInjectorRate: 0,
        targetProducerRate: 0,
        injectorI: 0,
        injectorJ: 0,
        producerI: 95,
        producerJ: 0,
        well_radius: 0.1,
        well_skin: 0,
        // Numerics
        delta_t_days: 0.25,
        steps: 200,
        max_sat_change_per_step: 0.05,
        max_pressure_change_per_step: 75,
        max_well_rate_change_fraction: 0.75,
        // Physics toggles
        gravityEnabled: false,
    },
    sensitivities: [
        {
            key: 'mobility',
            label: 'Mobility Ratio',
            description: 'Vary oil viscosity to explore how the end-point mobility ratio M = (k_rw/μ_w)/(k_ro/μ_o) controls breakthrough timing, watercut shape, and recovery. Both simulation and analytical solution update.',
            variants: [
                {
                    key: 'mob_favorable',
                    label: 'M ≈ 1  (μ_o = 0.5 cp)',
                    description: 'Near-unit mobility ratio — sharp, piston-like displacement. Best waterflood recovery.',
                    paramPatch: { mu_o: 0.5 },
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_base',
                    label: 'M ≈ 2  (μ_o = 1.0 cp)',
                    description: 'Base case — moderate unfavourable mobility. BL shock at S_w ≈ 0.55.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_case_b',
                    label: 'M ≈ 2.3  and tighter rock (Case B)',
                    description: 'BL Case B — adverse mobility with tighter rock (μ_o=1.4, μ_w=0.6, n_w=2.2, s_wc=s_or=0.15). Earlier breakthrough than base.',
                    paramPatch: { mu_w: 0.6, mu_o: 1.4, initialSaturation: 0.15, s_wc: 0.15, s_or: 0.15, n_w: 2.2 },
                    affectsAnalytical: true,
                },
                {
                    key: 'mob_unfavorable',
                    label: 'M ≈ 10  (μ_o = 5.0 cp)',
                    description: 'Strongly unfavourable — very early breakthrough relative to injected volume (PVI), poor recovery. Classic viscous fingering regime.',
                    paramPatch: { mu_o: 5.0 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'corey_no',
            label: 'Corey Exponent n_o',
            description: 'The Corey exponent controls the curvature of k_ro(S_w). Higher n_o → more convex k_ro → oil transmits less readily at intermediate saturations. Both simulation and analytical update.',
            variants: [
                {
                    key: 'no_15',
                    label: 'n_o = 1.5  (near-linear)',
                    description: 'Near-linear k_ro — oil transmits readily at intermediate saturations, slower BL shock.',
                    paramPatch: { n_o: 1.5 },
                    affectsAnalytical: true,
                },
                {
                    key: 'no_20',
                    label: 'n_o = 2.0  (base)',
                    description: 'Standard Corey exponent — base case.',
                    paramPatch: {},
                    affectsAnalytical: true,
                },
                {
                    key: 'no_35',
                    label: 'n_o = 3.5  (convex)',
                    description: 'Strongly convex k_ro — oil permeability collapses quickly near residual, earlier breakthrough.',
                    paramPatch: { n_o: 3.5 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'sor',
            label: 'Residual Oil  S_or',
            description: 'S_or sets the ceiling on waterflood recovery: RF_max = (1 − S_wc − S_or)/(1 − S_wc). Also shifts the fractional flow curve endpoint. Both simulation and analytical update.',
            variants: [
                {
                    key: 'sor_low',
                    label: 'S_or = 0.05  (low trapping)',
                    description: 'Low residual trapping — high recovery ceiling, typical of clean sandstone.',
                    paramPatch: { s_or: 0.05 },
                    affectsAnalytical: true,
                },
                {
                    key: 'sor_mid',
                    label: 'S_or = 0.15  (base)',
                    description: 'Moderate residual oil — base case.',
                    paramPatch: { s_or: 0.15 },
                    affectsAnalytical: true,
                },
                {
                    key: 'sor_high',
                    label: 'S_or = 0.30  (high trapping)',
                    description: 'High residual trapping — poor recovery ceiling, typical of carbonates or tight rock.',
                    paramPatch: { s_or: 0.30 },
                    affectsAnalytical: true,
                },
            ],
        },
        {
            key: 'grid',
            label: 'Grid Resolution',
            description: 'Numerical convergence study. The Buckley-Leverett analytical solution is grid-independent — only the simulation changes as the grid is refined.',
            chartPresetOverride: 'waterflood',
            variants: [
                {
                    key: 'grid_3',
                    label: '3 cells  (coarse)',
                    description: 'Coarse 3-cell grid — large numerical diffusion, smeared front.',
                    paramPatch: { nx: 3, producerI: 2, cellDx: 320 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_6',
                    label: '6 cells  (coarse)',
                    description: 'Coarse 6-cell grid — large numerical diffusion, smeared front.',
                    paramPatch: { nx: 6, producerI: 5, cellDx: 160 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_24',
                    label: '24 cells  (coarse)',
                    description: 'Coarse 24-cell grid — large numerical diffusion, smeared front.',
                    paramPatch: { nx: 24, producerI: 23, cellDx: 40 },
                    affectsAnalytical: false,
                },
                {
                    key: 'grid_96',
                    label: '96 cells  (fine)',
                    description: 'Fine 96-cell reference grid — matches the base case exactly.',
                    paramPatch: {},
                    affectsAnalytical: false,
                },
            ],
        },
    ],
};
