from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[3]

# Provenance recorded in every artifact before it is bundled (#20). Every deck
# here is written in this repository; none is a copy of a third-party deck.
ORIGIN_RESSIM = (
    "Deck written in this repository from the ResSim scenario's own parameters; no third-party "
    "data. Distributed under the repository licence (AGPL-3.0)."
)
ORIGIN_SMALL_DIRECT = (
    "Deck generated by src/lib/ressim/src/tests/opm_small_direct.rs from the same ResSim "
    "simulator object the scenario configures, sampling ResSim's own relperm and PVT functions; "
    "no third-party data. Distributed under the repository licence (AGPL-3.0)."
)
ORIGIN_SPE1 = (
    "Model inputs from the published SPE1 comparative solution project (Odeh, A.S., 1981, "
    "'Comparison of Solutions to a Three-Dimensional Black-Oil Reservoir Simulation Problem', "
    "JPT 33(1), SPE-9723-PA), converted to METRIC. The deck is written in this repository, not "
    "copied from OPM's SPE1CASE1.DATA. Distributed under the repository licence (AGPL-3.0)."
)


@dataclass(frozen=True)
class OpmCase:
    key: str
    scenario_key: str
    label: str
    deck_name: str
    supported_curves: tuple[str, ...]
    deck: str
    # Maps a parsed summary vector's curve_id (mnemonic, or "MNEMONIC:NAME"
    # for well/group vectors) to how the frontend should display it. Keys
    # must be a subset of what the deck's SUMMARY section actually requests;
    # `build_artifact()` treats an unmapped-but-present vector as ignored,
    # not an error, so this can be extended incrementally.
    curve_display: dict[str, dict[str, str]]
    # Cumulative *reservoir*-volume injection vector (FVIT, unit RM3) and the
    # deck's pore volume. Together they let `build_artifact()` publish the
    # time -> PVI mapping of this run, so the frontend can draw the reference
    # curves on a pore-volumes-injected axis instead of only against days.
    # Both must be present for the mapping to be emitted; a case with no
    # injector legitimately has neither.
    cumulative_injection_curve: str | None = None
    # Grid pore volume in m3: DIMENS x DXV x DYV x DZV x PORO of this deck.
    # Declared rather than parsed — the deck text is the source of truth, and a
    # scenario test cross-checks it against the ResSim case it mirrors.
    pore_volume_m3: float | None = None
    # Cumulative *surface* gas production vector (FGPT, unit SM3). Lets
    # `build_artifact()` publish a time -> cumulative-gas mapping, which is what
    # a p/z chart needs: its x-axis is produced gas, not time or injection.
    cumulative_gas_curve: str | None = None
    # Cumulative *surface* injection vector (FWIT or FGIT, unit SM3): the basis of
    # ResSim's own cumulative-injection curve and axis. PVI stays on the
    # reservoir-volume vector above; the two differ by the injected phase's FVF.
    cumulative_surface_injection_curve: str | None = None
    # Repo-relative path the deck text comes from.
    deck_source: str = "tools/opm_flow/opm_flow_tool/cases.py"
    # Extra Flow options the deck must be run with, recorded for replay.
    flow_args: tuple[str, ...] = ()
    # Where the model inputs come from and under what terms.
    origin: str = ORIGIN_RESSIM


def _committed_deck(path: str) -> str:
    return (REPO_ROOT / path).read_text(encoding="utf-8")


def _clean_deck(text: str) -> str:
    return dedent(text).strip() + "\n"


WF_BL1D = OpmCase(
    key="wf_bl1d",
    scenario_key="wf_bl1d",
    label="1D Waterflood IMPES Reference-Compatible Case",
    deck_name="WF_BL1D.DATA",
    supported_curves=("FWCT", "FOPR", "FWPR", "FWIR", "FOPT", "FWPT", "FWIT", "FVIT", "FPR"),
    cumulative_injection_curve="FVIT",
    cumulative_surface_injection_curve="FWIT",
    # 96 x 10 m by 1 x 10 m by 1 x 1 m at 0.2 porosity.
    pore_volume_m3=1_920.0,
    # The waterflood layout's `rates` panel is water cut, a fraction. This case
    # used to put FOPR, FWPR and FWIR there in Sm3/day, which is one reason it
    # was taken off the scenario; each vector now lands beside the ResSim curve
    # of the same quantity (#20).
    curve_display={
        "FWCT": {"panelKey": "rates", "curveKey": "opm-water-cut", "label": "OPM Flow — Water Cut"},
        "FOPR": {"panelKey": "oil_rate", "curveKey": "opm-oil-rate", "label": "OPM Flow — Oil Rate"},
        "FOPT": {"panelKey": "cumulative", "curveKey": "opm-cum-oil", "label": "OPM Flow — Cum Oil"},
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-avg-pressure", "label": "OPM Flow — Avg Pressure"},
        "FWIT": {"panelKey": "volumes", "curveKey": "opm-cum-injection", "label": "OPM Flow — Cum Water Injection"},
    },
    deck=_clean_deck(
        """
        RUNSPEC
        TITLE
          RESSIM WF_BL1D OPM FLOW REFERENCE /
        DIMENS
          96 1 1 /
        OIL
        WATER
        METRIC
        TABDIMS
          1 1 20 20 1 20 /
        WELLDIMS
          2 2 1 2 /
        START
          1 JAN 2026 /
        GRID
        DXV
          96*10 /
        DYV
          1*10 /
        DZV
          1*1 /
        TOPS
          96*0 /
        PORO
          96*0.2 /
        PERMX
          96*2000 /
        PERMY
          96*2000 /
        PERMZ
          96*200 /
        PROPS
        PVTW
          300 1.0 3E-6 0.5 0 /
        PVDO
          100 1.002 1.0
          300 1.000 1.0
          500 0.998 1.0 /
        DENSITY
          800 1000 1 /
        SWOF
          0.10 0.0 1.0 0
          0.20 0.015625 0.765625 0
          0.30 0.0625 0.5625 0
          0.40 0.140625 0.390625 0
          0.50 0.25 0.25 0
          0.60 0.390625 0.140625 0
          0.70 0.5625 0.0625 0
          0.80 0.765625 0.015625 0
          0.90 1.0 0.0 0 /
        REGIONS
        SOLUTION
        EQUIL
          0 300 10000 0 0 0 0 0 0 /
        SUMMARY
        FWCT
        FOPR
        FWPR
        FWIR
        FOPT
        FWPT
        FWIT
        FVIT
        FPR
        RUNSUM
        SEPARATE
        SCHEDULE
        RPTRST
          BASIC=2 /
        WELSPECS
          'INJ' 'G' 1 1 0 'WATER' /
          'PROD' 'G' 96 1 0 'OIL' /
        /
        COMPDAT
        -- Items 7-8 (SATNUM, connection transmissibility factor) are defaulted so
        -- Flow computes the Peaceman factor itself; item 9 is the wellbore
        -- DIAMETER (2 x the ResSim scenario's 0.1 m well_radius).
          'INJ' 1 1 1 1 'OPEN' 2* 0.2 /
          'PROD' 96 1 1 1 'OPEN' 2* 0.2 /
        /
        WCONINJE
          'INJ' 'WATER' 'OPEN' 'BHP' 1* 1* 500 /
        /
        WCONPROD
          'PROD' 'OPEN' 'BHP' 5* 100 /
        /
        TSTEP
          200*0.25 /
        END
        """
    ),
)


SPE1_GAS_INJECTION = OpmCase(
    key="spe1_gas_injection",
    scenario_key="spe1_gas_injection",
    label="SPE1 Black-Oil Benchmark",
    deck_name="SPE1_GAS_INJECTION.DATA",
    supported_curves=("FOPR", "FGIR", "FOPT", "FGPT", "FPR", "WBHP", "WGOR"),
    origin=ORIGIN_SPE1,
    curve_display={
        "FOPR": {"panelKey": "oil_rate", "curveKey": "opm-oil-rate", "label": "OPM Flow — Oil Rate"},
        "FGIR": {"panelKey": "injection_rate", "curveKey": "opm-gas-injection-rate", "label": "OPM Flow — Gas Injection Rate"},
        "FOPT": {"panelKey": "cumulative", "curveKey": "opm-cum-oil", "label": "OPM Flow — Cum Oil"},
        "FGPT": {"panelKey": "cumulative_gas", "curveKey": "opm-cum-gas", "label": "OPM Flow — Cum Gas"},
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-avg-pressure", "label": "OPM Flow — Avg Pressure"},
        "WBHP:INJ": {"panelKey": "injector_bhp", "curveKey": "opm-injector-bhp", "label": "OPM Flow — Injector BHP"},
        "WBHP:PROD": {"panelKey": "producer_bhp", "curveKey": "opm-producer-bhp", "label": "OPM Flow — Producer BHP"},
        "WGOR:PROD": {"panelKey": "gor", "curveKey": "opm-gor", "label": "OPM Flow — GOR"},
    },
    deck=_clean_deck(
        """
        RUNSPEC
        TITLE
          RESSIM SPE1 GAS INJECTION OPM FLOW REFERENCE SKELETON /
        DIMENS
          10 10 3 /
        OIL
        WATER
        GAS
        DISGAS
        METRIC
        TABDIMS
          1 1 20 20 1 20 /
        EQLDIMS
        /
        WELLDIMS
          2 2 1 2 /
        START
          1 JAN 2026 /
        GRID
        DXV
          10*304.8 /
        DYV
          10*304.8 /
        DZ
          100*6.096 100*9.144 100*15.24 /
        -- 8325 ft: the true SPE1 reservoir top. Needed so the WELSPECS datum
        -- depths below sit inside the grid and BHP is reported at the same
        -- datum the ResSim scenario uses (depth_reference 2560 m).
        TOPS
          100*2537.46 /
        PORO
          300*0.3 /
        PERMX
          100*500 100*50 100*200 /
        PERMY
          100*500 100*50 100*200 /
        PERMZ
          100*500 100*50 100*200 /
        PROPS
        -- This skeleton is generated from the ResSim SPE1 scenario. Keep the
        -- authoritative SPE1 deck-matching work in this tool rather than the UI.
        DENSITY
          860 1033 0.854 /
        PVTW
          331 1.038 4.67E-5 0.318 0 /
        -- SPE1CASE1.DATA: 14.7 psia, 3E-6 /psi (Odeh, Table 1). It was missing until
        -- #55, so Flow ran incompressible rock: pressure +3.6 %, GOR -15 % on its own.
        ROCK
          1.01353 4.35114E-5 /
        PVTO
          0.18 1.01 1.062 1.040 /
          16.12 18.25 1.150 0.975 /
          32.06 35.49 1.207 0.910 /
          66.08 69.96 1.295 0.830 /
          113.29 138.91 1.435 0.695 /
          138.03 173.38 1.500 0.641 /
          165.64 207.85 1.565 0.594 /
          226.20 276.79 1.695 0.510
                 621.54 1.579 0.740 /
          288.17 345.73 1.827 0.449
                 621.54 1.737 0.631 /
        /
        PVDG
          1.01 0.9361 0.0080
          18.25 0.0679 0.0096
          35.49 0.0352 0.0112
          69.96 0.0179 0.0140
          138.91 0.00906 0.0189
          173.38 0.00727 0.0208
          207.85 0.00607 0.0228
          276.79 0.00455 0.0268
          345.73 0.00364 0.0309
          621.54 0.002167 0.0470 /
        -- SWOF and SGOF carry every row of SPE1CASE1.DATA (#55: seven SWOF and five SGOF
        -- rows had been dropped, and Flow interpolated linearly across the gaps).
        SWOF
          0.12 0 1 0
          0.18 4.64876033057851E-8 1 0
          0.24 1.86E-7 0.997 0
          0.30 4.18388429752066E-7 0.98 0
          0.36 7.43801652892562E-7 0.7 0
          0.42 1.16219008264463E-6 0.35 0
          0.48 1.67355371900826E-6 0.2 0
          0.54 2.27789256198347E-6 0.09 0
          0.60 2.97520661157025E-6 0.021 0
          0.66 3.7654958677686E-6 0.01 0
          0.72 4.64876033057851E-6 0.001 0
          0.78 5.625E-6 0.0001 0
          0.84 6.69421487603306E-6 0 0
          0.91 8.05914256198347E-6 0 0
          1.00 1E-5 0 0 /
        SGOF
          0 0 1 0
          0.001 0 1 0
          0.02 0 0.997 0
          0.05 0.005 0.980 0
          0.12 0.025 0.700 0
          0.20 0.075 0.350 0
          0.25 0.125 0.200 0
          0.30 0.190 0.090 0
          0.40 0.410 0.021 0
          0.45 0.60 0.010 0
          0.50 0.72 0.001 0
          0.60 0.87 0.0001 0
          0.70 0.94 0.000 0
          0.85 0.98 0.000 0
          0.88 0.984 0.000 0 /
        SOLUTION
        -- Datum 8400 ft / 4800 psia, WOC just below (8450 ft) and GOC just
        -- above (8300 ft) the reservoir, as in Odeh's Table 1.
        EQUIL
          2560.32 331 2575.56 0 2529.84 0 1 0 0 /
        -- Undersaturated: Rs is constant with depth (bubble point 4014.7 psia
        -- < 4800 psia initial), so both bracketing depths carry the same Rs.
        RSVD
          2529.84 226.197
          2575.56 226.197 /
        SUMMARY
        FOPR
        FGIR
        FOPT
        FGPT
        FPR
        WBHP
          'INJ' 'PROD' /
        WGOR
          'PROD' /
        RUNSUM
        SEPARATE
        SCHEDULE
        -- Case 1: no re-dissolution of free gas, matching the ResSim
        -- scenario's gasRedissolutionEnabled: false.
        DRSDT
          0 /
        -- Datum depths are the perforated layer centres: 8335 ft (layer 1) for
        -- the injector, 8400 ft (layer 3) for the producer.
        WELSPECS
          'INJ' 'G' 1 1 2540.51 'GAS' /
          'PROD' 'G' 10 10 2560.32 'OIL' /
        /
        COMPDAT
        -- Items 7-8 (SATNUM, connection transmissibility factor) are defaulted so
        -- Flow computes the Peaceman factor itself; item 9 is the wellbore
        -- DIAMETER (0.5 ft = 2 x the deck's 0.25 ft well radius).
          'INJ' 1 1 1 1 'OPEN' 2* 0.1524 /
          'PROD' 10 10 3 3 'OPEN' 2* 0.1524 /
        /
        WCONINJE
          'INJ' 'GAS' 'OPEN' 'RATE' 2831680 1* 621 /
        /
        WCONPROD
          'PROD' 'OPEN' 'ORAT' 3179.74 4* 69 /
        /
        TSTEP
          120*30 /
        END
        """
    ),
)


GAS_DRIVE = OpmCase(
    key="gas_drive",
    scenario_key="gas_drive",
    label="Solution Gas Drive Black-Oil Reference",
    deck_name="GAS_DRIVE.DATA",
    supported_curves=("FOPR", "FGPR", "FOPT", "FGPT", "FPR", "FGOR"),
    # FGPR/FGPT were requested in SUMMARY but left unmapped until 2026-08-02,
    # because gas rate and cumulative gas are ~3 orders of magnitude larger than
    # their oil counterparts and would have flattened the simulated curves on the
    # shared `rates` / `cumulative` axes. That objection expired when the gas
    # quantities got panels of their own: OPM's gas now lands beside ResSim's gas
    # on `gas_rate` / `cumulative_gas`, one property per axis, and the reference
    # covers every panel of this scenario that OPM reports rather than four of six.
    curve_display={
        "FOPR": {"panelKey": "rates", "curveKey": "opm-oil-rate", "label": "OPM Flow — Oil Rate"},
        "FOPT": {"panelKey": "cumulative", "curveKey": "opm-cum-oil", "label": "OPM Flow — Cum Oil"},
        "FGPR": {"panelKey": "gas_rate", "curveKey": "opm-gas-rate", "label": "OPM Flow — Gas Rate"},
        "FGPT": {"panelKey": "cumulative_gas", "curveKey": "opm-cum-gas", "label": "OPM Flow — Cum Gas"},
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-avg-pressure", "label": "OPM Flow — Avg Pressure"},
        "FGOR": {"panelKey": "gor", "curveKey": "opm-gor", "label": "OPM Flow — GOR"},
    },
    # Generated from the acceptance test's simulator, which mirrors the scenario's base case (#55).
    # The hand-written deck this replaces sampled the Corey SGOF at ten nodes; between S_gc = 0.05
    # and 0.1286 Flow's linear interpolation overstated k_rg by up to 41 %, and the case starts at
    # S_g = 0.08, so its reference was 4-6 % off the model it was meant to grade.
    deck_source="opm/reference-decks/small-direct/gas-drive-20/CASE.DATA",
    deck=_committed_deck("opm/reference-decks/small-direct/gas-drive-20/CASE.DATA"),
    flow_args=("--enable-gravity=false",),
    origin=ORIGIN_SMALL_DIRECT,
)


WF_GRAVITY = OpmCase(
    key="wf_gravity",
    scenario_key="wf_gravity",
    label="Gravity Override Cross-Section (base case)",
    deck_name="WF_GRAVITY.DATA",
    supported_curves=("FWCT", "FOPR", "FWPR", "FWIR", "FOPT", "FWPT", "FWIT", "FVIT", "FPR"),
    cumulative_injection_curve="FVIT",
    cumulative_surface_injection_curve="FWIT",
    # 30 x 10 m by 1 x 20 m by 20 x 2 m at 0.2 porosity.
    pore_volume_m3=48_000.0,
    curve_display={
        # Panels carry one property each, so only the vectors with a ResSim
        # counterpart in the waterflood layout are displayed: water cut, oil
        # rate, cumulative oil and average pressure. The rest stay in the
        # summary for provenance.
        "FWCT": {"panelKey": "rates", "curveKey": "opm-water-cut", "label": "OPM Flow — Water Cut"},
        "FOPR": {"panelKey": "oil_rate", "curveKey": "opm-oil-rate", "label": "OPM Flow — Oil Rate"},
        "FOPT": {"panelKey": "cumulative", "curveKey": "opm-cum-oil", "label": "OPM Flow — Cum Oil"},
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-avg-pressure", "label": "OPM Flow — Avg Pressure"},
    },
    deck=_clean_deck(
        """
        RUNSPEC
        TITLE
          RESSIM WF_GRAVITY OPM FLOW REFERENCE /
        DIMENS
          30 1 20 /
        OIL
        WATER
        METRIC
        TABDIMS
          1 1 20 20 1 20 /
        EQLDIMS
        /
        WELLDIMS
          2 2 1 2 /
        START
          1 JAN 2026 /
        GRID
        DXV
          30*10 /
        DYV
          1*20 /
        DZV
          20*2 /
        TOPS
          30*0 /
        PORO
          600*0.2 /
        PERMX
          600*5000 /
        PERMY
          600*5000 /
        PERMZ
          600*5000 /
        PROPS
        PVTW
          300 1.0 3E-6 0.5 0 /
        PVDO
          100 1.002 1.0
          300 1.000 1.0
          500 0.998 1.0 /
        ROCK
          300 1E-6 /
        DENSITY
          800 1000 1 /
        -- Corey n_w = n_o = 2, S_wc = S_or = 0.1, end points 1.0, zero capillary
        -- pressure: the same rock curves as the ResSim wf_gravity scenario.
        SWOF
          0.10 0.0 1.0 0
          0.20 0.015625 0.765625 0
          0.30 0.0625 0.5625 0
          0.40 0.140625 0.390625 0
          0.50 0.25 0.25 0
          0.60 0.390625 0.140625 0
          0.70 0.5625 0.0625 0
          0.80 0.765625 0.015625 0
          0.90 1.0 0.0 0 /
        REGIONS
        SOLUTION
        -- Datum at the mid-depth of the 40 m section so the initial hydrostatic
        -- field averages the ResSim scenario's uniform 300 bar. Water contact is
        -- placed far below the model, leaving every cell at connate water.
        EQUIL
          20 300 10000 0 0 0 0 0 0 /
        SUMMARY
        FWCT
        FOPR
        FWPR
        FWIR
        FOPT
        FWPT
        FWIT
        FVIT
        FPR
        RUNSUM
        SEPARATE
        SCHEDULE
        RPTRST
          BASIC=2 /
        -- One perforation per well, both in the bottom layer: the ResSim engine
        -- applies no wellbore hydrostatic correction across completions, so the
        -- comparison is only well-model-neutral with a single connection each.
        WELSPECS
          'INJ' 'G' 1 1 39 'WATER' /
          'PROD' 'G' 30 1 39 'OIL' /
        /
        COMPDAT
          'INJ' 1 1 20 20 'OPEN' 2* 0.2 /
          'PROD' 30 1 20 20 'OPEN' 2* 0.2 /
        /
        WCONINJE
          'INJ' 'WATER' 'OPEN' 'RATE' 160 1* 600 /
        /
        WCONPROD
          'PROD' 'OPEN' 'BHP' 5* 200 /
        /
        TSTEP
          210*2 /
        END
        """
    ),
)


WF_NUMERICS = OpmCase(
    key="wf_numerics",
    scenario_key="wf_numerics",
    label="Numerical Dispersion Column (base grid, 50 cells)",
    deck_name="WF_NUMERICS.DATA",
    supported_curves=("FWCT", "FOPR", "FWPR", "FWIR", "FOPT", "FWPT", "FWIT", "FVIT", "FPR"),
    cumulative_injection_curve="FVIT",
    cumulative_surface_injection_curve="FWIT",
    # 50 x 10 m by 1 x 20 m by 1 x 10 m at 0.2 porosity.
    pore_volume_m3=20_000.0,
    curve_display={
        "FWCT": {"panelKey": "rates", "curveKey": "opm-water-cut", "label": "OPM Flow \u2014 Water Cut (\u0394x = 10 m)"},
        "FOPR": {"panelKey": "oil_rate", "curveKey": "opm-oil-rate", "label": "OPM Flow \u2014 Oil Rate (\u0394x = 10 m)"},
        "FOPT": {"panelKey": "cumulative", "curveKey": "opm-cum-oil", "label": "OPM Flow \u2014 Cum Oil (\u0394x = 10 m)"},
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-avg-pressure", "label": "OPM Flow \u2014 Avg Pressure (\u0394x = 10 m)"},
    },
    deck=_clean_deck(
        """
        RUNSPEC
        TITLE
          RESSIM WF_NUMERICS OPM FLOW REFERENCE (50 cells) /
        DIMENS
          50 1 1 /
        OIL
        WATER
        METRIC
        TABDIMS
          1 1 20 20 1 20 /
        EQLDIMS
        /
        WELLDIMS
          2 2 1 2 /
        START
          1 JAN 2026 /
        GRID
        DXV
          50*10 /
        DYV
          1*20 /
        DZV
          1*10 /
        TOPS
          50*0 /
        PORO
          50*0.2 /
        PERMX
          50*500 /
        PERMY
          50*500 /
        PERMZ
          50*500 /
        PROPS
        PVTW
          300 1.0 3E-6 0.5 0 /
        PVDO
          100 1.002 1.0
          300 1.000 1.0
          500 0.998 1.0 /
        ROCK
          300 1E-6 /
        DENSITY
          800 1000 1 /
        -- Corey n_w = n_o = 2, S_wc = S_or = 0.1, end points 1.0, zero capillary
        -- pressure: the same rock curves as the ResSim wf_numerics scenario.
        SWOF
          0.10 0.0 1.0 0
          0.20 0.015625 0.765625 0
          0.30 0.0625 0.5625 0
          0.40 0.140625 0.390625 0
          0.50 0.25 0.25 0
          0.60 0.390625 0.140625 0
          0.70 0.5625 0.0625 0
          0.80 0.765625 0.015625 0
          0.90 1.0 0.0 0 /
        REGIONS
        SOLUTION
        -- Datum at the cell centre of the single 10 m layer, so the initial
        -- hydrostatic field reproduces the scenario's uniform 300 bar. The water
        -- contact is far below the model, leaving every cell at connate water.
        EQUIL
          5 300 10000 0 0 0 0 0 0 /
        SUMMARY
        FWCT
        FOPR
        FWPR
        FWIR
        FOPT
        FWPT
        FWIT
        FVIT
        FPR
        RUNSUM
        SEPARATE
        SCHEDULE
        RPTRST
          BASIC=2 /
        WELSPECS
          'INJ' 'G' 1 1 5 'WATER' /
          'PROD' 'G' 50 1 5 'OIL' /
        /
        COMPDAT
          'INJ' 1 1 1 1 'OPEN' 2* 0.2 /
          'PROD' 50 1 1 1 'OPEN' 2* 0.2 /
        /
        -- Reservoir-volume rate control, matching the scenario's 100 m3/day of
        -- injected reservoir volume; 700 bar is the ResSim injector BHP limit.
        WCONINJE
          'INJ' 'WATER' 'OPEN' 'RESV' 1* 100 700 /
        /
        WCONPROD
          'PROD' 'OPEN' 'BHP' 5* 200 /
        /
        TSTEP
          260*1 /
        END
"""
    ),
)


# The same physical column at the scenario's converged resolution. Shipped as a
# separate case rather than a variant because one artifact carries one run, and
# the pair is the point: OPM Flow has its own grid-convergence path to the same
# analytical answer.
WF_NUMERICS_FINE = OpmCase(
    key="wf_numerics_fine",
    scenario_key="wf_numerics",
    label="Numerical Dispersion Column (fine grid, 200 cells)",
    deck_name="WF_NUMERICS_FINE.DATA",
    supported_curves=("FWCT", "FOPR", "FWPR", "FWIR", "FOPT", "FWPT", "FWIT", "FVIT", "FPR"),
    cumulative_injection_curve="FVIT",
    cumulative_surface_injection_curve="FWIT",
    pore_volume_m3=20_000.0,
    curve_display={
        "FWCT": {"panelKey": "rates", "curveKey": "opm-fine-water-cut", "label": "OPM Flow \u2014 Water Cut (\u0394x = 2.5 m)"},
        "FOPR": {"panelKey": "oil_rate", "curveKey": "opm-fine-oil-rate", "label": "OPM Flow \u2014 Oil Rate (\u0394x = 2.5 m)"},
        "FOPT": {"panelKey": "cumulative", "curveKey": "opm-fine-cum-oil", "label": "OPM Flow \u2014 Cum Oil (\u0394x = 2.5 m)"},
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-fine-avg-pressure", "label": "OPM Flow \u2014 Avg Pressure (\u0394x = 2.5 m)"},
    },
    deck=_clean_deck(
        """
        RUNSPEC
        TITLE
          RESSIM WF_NUMERICS OPM FLOW REFERENCE (200 cells) /
        DIMENS
          200 1 1 /
        OIL
        WATER
        METRIC
        TABDIMS
          1 1 20 20 1 20 /
        EQLDIMS
        /
        WELLDIMS
          2 2 1 2 /
        START
          1 JAN 2026 /
        GRID
        DXV
          200*2.5 /
        DYV
          1*20 /
        DZV
          1*10 /
        TOPS
          200*0 /
        PORO
          200*0.2 /
        PERMX
          200*500 /
        PERMY
          200*500 /
        PERMZ
          200*500 /
        PROPS
        PVTW
          300 1.0 3E-6 0.5 0 /
        PVDO
          100 1.002 1.0
          300 1.000 1.0
          500 0.998 1.0 /
        ROCK
          300 1E-6 /
        DENSITY
          800 1000 1 /
        -- Corey n_w = n_o = 2, S_wc = S_or = 0.1, end points 1.0, zero capillary
        -- pressure: the same rock curves as the ResSim wf_numerics scenario.
        SWOF
          0.10 0.0 1.0 0
          0.20 0.015625 0.765625 0
          0.30 0.0625 0.5625 0
          0.40 0.140625 0.390625 0
          0.50 0.25 0.25 0
          0.60 0.390625 0.140625 0
          0.70 0.5625 0.0625 0
          0.80 0.765625 0.015625 0
          0.90 1.0 0.0 0 /
        REGIONS
        SOLUTION
        -- Datum at the cell centre of the single 10 m layer, so the initial
        -- hydrostatic field reproduces the scenario's uniform 300 bar. The water
        -- contact is far below the model, leaving every cell at connate water.
        EQUIL
          5 300 10000 0 0 0 0 0 0 /
        SUMMARY
        FWCT
        FOPR
        FWPR
        FWIR
        FOPT
        FWPT
        FWIT
        FVIT
        FPR
        RUNSUM
        SEPARATE
        SCHEDULE
        RPTRST
          BASIC=2 /
        WELSPECS
          'INJ' 'G' 1 1 5 'WATER' /
          'PROD' 'G' 200 1 5 'OIL' /
        /
        COMPDAT
          'INJ' 1 1 1 1 'OPEN' 2* 0.2 /
          'PROD' 200 1 1 1 'OPEN' 2* 0.2 /
        /
        -- Reservoir-volume rate control, matching the scenario's 100 m3/day of
        -- injected reservoir volume; 700 bar is the ResSim injector BHP limit.
        WCONINJE
          'INJ' 'WATER' 'OPEN' 'RESV' 1* 100 700 /
        /
        WCONPROD
          'PROD' 'OPEN' 'BHP' 5* 200 /
        /
        TSTEP
          260*1 /
        END
"""
    ),
)


# The p/z case's own deck, and the geopressured rung of its compressibility
# ladder. Two cases rather than one because an artifact carries one run, and the
# pair is the point: ROCK is a first-class Eclipse keyword, so an independent
# simulator can be asked whether the reserves error really tracks c_f.
DEP_GAS_PZ = OpmCase(
    key="dep_gas_pz",
    scenario_key="dep_gas_pz",
    label="Dry-Gas Depletion (c_f = 5e-6 /bar, base)",
    deck_name="DEP_GAS_PZ.DATA",
    supported_curves=("FGPR", "FGPT", "FWPR", "FPR", "FGIP"),
    cumulative_gas_curve="FGPT",
    curve_display={
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-avg-pressure", "label": "OPM Flow \u2014 Avg Pressure (c_f = 5e-6)"},
        "FGPR": {"panelKey": "gas_rate", "curveKey": "opm-gas-rate", "label": "OPM Flow \u2014 Gas Rate (c_f = 5e-6)"},
    },
    deck=_clean_deck(
        """
        RUNSPEC
        TITLE
          RESSIM DEP_GAS_PZ OPM FLOW REFERENCE (c_f = 5e-6 /bar) /
        DIMENS
          20 1 5 /
        -- Dry gas over connate water. The ResSim scenario runs its three-phase
        -- machinery with S_o = 0 throughout; OPM models the same reservoir as a
        -- genuine two-phase gas/water system, which is the same physics with one
        -- fewer inert equation.
        GAS
        WATER
        METRIC
        TABDIMS
          1 1 60 60 1 60 /
        EQLDIMS
        /
        WELLDIMS
          1 5 1 1 /
        START
          1 JAN 2026 /
        GRID
        DXV
          20*100 /
        DYV
          1*100 /
        DZV
          5*4 /
        TOPS
          20*0 /
        PORO
          100*0.15 /
        PERMX
          100*5 /
        PERMY
          100*5 /
        PERMZ
          100*0.5 /
        PROPS
        -- Generated from the ResSim scenario's own `pvtTable`, so both simulators
        -- integrate one gas law. A test pins these rows against that table.
        PVDG
          1.0000 1.27487388e+0 0.01339192
          7.6271 1.65677785e-1 0.01343762
          15.2542 8.21231756e-2 0.01351589
          20.0000 6.23048775e-2 0.01357423
          30.5085 4.03787793e-2 0.01372515
          38.1356 3.20441594e-2 0.01385159
          45.7627 2.64963503e-2 0.01399121
          53.3898 2.25414782e-2 0.01414350
          61.0169 1.95826239e-2 0.01430810
          68.6441 1.72881762e-2 0.01448475
          76.2712 1.54591732e-2 0.01467323
          83.8983 1.39690017e-2 0.01487335
          91.5254 1.27332466e-2 0.01508489
          99.1525 1.16934563e-2 0.01530763
          106.7797 1.08078644e-2 0.01554129
          114.4068 1.00458234e-2 0.01578554
          122.0339 9.38432554e-3 0.01604001
          129.6610 8.80575223e-3 0.01630426
          137.2881 8.29637365e-3 0.01657779
          144.9153 7.84532318e-3 0.01686007
          152.5424 7.44388001e-3 0.01715048
          160.1695 7.08495761e-3 0.01744840
          167.7966 6.76273237e-3 0.01775316
          175.4237 6.47236994e-3 0.01806405
          183.0508 6.20982051e-3 0.01838038
          190.6780 5.97166384e-3 0.01870144
          198.3051 5.75499033e-3 0.01902655
          205.9322 5.55730882e-3 0.01935503
          213.5593 5.37647420e-3 0.01968624
          221.1864 5.21063007e-3 0.02001956
          228.8136 5.05816269e-3 0.02035442
          236.4407 4.91766380e-3 0.02069030
          244.0678 4.78790010e-3 0.02102672
          251.6949 4.66778821e-3 0.02136321
          259.3220 4.55637369e-3 0.02169940
          266.9492 4.45281357e-3 0.02203493
          274.5763 4.35636156e-3 0.02236947
          282.2034 4.26635548e-3 0.02270277
          289.8305 4.18220654e-3 0.02303457
          297.4576 4.10339018e-3 0.02336468
          305.0847 4.02943811e-3 0.02369291
          312.7119 3.95993155e-3 0.02401912
          320.3390 3.89449525e-3 0.02434318
          327.9661 3.83279239e-3 0.02466500
          335.5932 3.77452008e-3 0.02498448
          343.2203 3.71940550e-3 0.02530157
          350.8475 3.66720248e-3 0.02561621
          358.4746 3.61768848e-3 0.02592837
          366.1017 3.57066205e-3 0.02623802
          373.7288 3.52594046e-3 0.02654515
          381.3559 3.48335773e-3 0.02684975
          388.9831 3.44276283e-3 0.02715182
          396.6102 3.40401815e-3 0.02745138
          404.2373 3.36699804e-3 0.02774843
          411.8644 3.33158768e-3 0.02804299
          419.4915 3.29768190e-3 0.02833509
          427.1186 3.26518431e-3 0.02862474
          434.7458 3.23400636e-3 0.02891198
          442.3729 3.20406666e-3 0.02919685
          450.0000 3.17529021e-3 0.02947936 /
        PVTW
          400 1.0 4E-5 0.4 0 /
        DENSITY
          800 1000 0.7951 /
        -- Pore compressibility at the initial pressure — the parameter this
        -- reference exists to arbitrate.
        ROCK
          400 5E-6 /
        -- Corey gas/water curves from the scenario's own end points:
        -- S_wc 0.2, S_gc 0.02, n_g 1.5, n_w 2, k_rg_max 0.9, k_rw_max 0.4.
        SGWFN
          0.000000 0.00000000 0.40000000 0
          0.040000 0.00369527 0.36100000 0
          0.080000 0.01920116 0.32400000 0
          0.120000 0.04131432 0.28900000 0
          0.160000 0.06843727 0.25600000 0
          0.200000 0.09977216 0.22500000 0
          0.240000 0.13481389 0.19600000 0
          0.280000 0.17320508 0.16900000 0
          0.320000 0.21467550 0.14400000 0
          0.360000 0.25901146 0.12100000 0
          0.400000 0.30603845 0.10000000 0
          0.440000 0.35561047 0.08100000 0
          0.480000 0.40760298 0.06400000 0
          0.520000 0.46190814 0.04900000 0
          0.560000 0.51843134 0.03600000 0
          0.600000 0.57708873 0.02500000 0
          0.640000 0.63780532 0.01600000 0
          0.680000 0.70051350 0.00900000 0
          0.720000 0.76515191 0.00400000 0
          0.760000 0.83166454 0.00100000 0
          0.800000 0.90000000 0.00000000 0 /
        REGIONS
        SOLUTION
        -- Datum at the mid-depth of the 20 m section. The gas/water contact is
        -- far below the model, so every cell initialises at connate water.
        EQUIL
          10 400 10000 0 0 0 0 0 0 /
        SUMMARY
        FGPR
        FGPT
        FWPR
        FPR
        FGIP
        RUNSUM
        SEPARATE
        SCHEDULE
        RPTRST
          BASIC=2 /
        -- One producer at the centre of the section, all five layers, on the
        -- same 30 bar abandonment pressure the scenario uses.
        WELSPECS
          'PROD' 'G' 11 1 10 'GAS' /
        /
        COMPDAT
          'PROD' 11 1 1 5 'OPEN' 2* 0.2 /
        /
        WCONPROD
          'PROD' 'OPEN' 'BHP' 5* 30 /
        /
        TSTEP
          200*20 /
        END
"""
    ),
)


DEP_GAS_PZ_GEOPRESSURED = OpmCase(
    key="dep_gas_pz_geopressured",
    scenario_key="dep_gas_pz",
    label="Dry-Gas Depletion (c_f = 5e-4 /bar, geopressured)",
    deck_name="DEP_GAS_PZ_GEOPRESSURED.DATA",
    supported_curves=("FGPR", "FGPT", "FWPR", "FPR", "FGIP"),
    cumulative_gas_curve="FGPT",
    curve_display={
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-geo-avg-pressure", "label": "OPM Flow \u2014 Avg Pressure (c_f = 5e-4)"},
        "FGPR": {"panelKey": "gas_rate", "curveKey": "opm-geo-gas-rate", "label": "OPM Flow \u2014 Gas Rate (c_f = 5e-4)"},
    },
    deck=_clean_deck(
        """
        RUNSPEC
        TITLE
          RESSIM DEP_GAS_PZ OPM FLOW REFERENCE (c_f = 5e-4 /bar) /
        DIMENS
          20 1 5 /
        -- Dry gas over connate water. The ResSim scenario runs its three-phase
        -- machinery with S_o = 0 throughout; OPM models the same reservoir as a
        -- genuine two-phase gas/water system, which is the same physics with one
        -- fewer inert equation.
        GAS
        WATER
        METRIC
        TABDIMS
          1 1 60 60 1 60 /
        EQLDIMS
        /
        WELLDIMS
          1 5 1 1 /
        START
          1 JAN 2026 /
        GRID
        DXV
          20*100 /
        DYV
          1*100 /
        DZV
          5*4 /
        TOPS
          20*0 /
        PORO
          100*0.15 /
        PERMX
          100*5 /
        PERMY
          100*5 /
        PERMZ
          100*0.5 /
        PROPS
        -- Generated from the ResSim scenario's own `pvtTable`, so both simulators
        -- integrate one gas law. A test pins these rows against that table.
        PVDG
          1.0000 1.27487388e+0 0.01339192
          7.6271 1.65677785e-1 0.01343762
          15.2542 8.21231756e-2 0.01351589
          20.0000 6.23048775e-2 0.01357423
          30.5085 4.03787793e-2 0.01372515
          38.1356 3.20441594e-2 0.01385159
          45.7627 2.64963503e-2 0.01399121
          53.3898 2.25414782e-2 0.01414350
          61.0169 1.95826239e-2 0.01430810
          68.6441 1.72881762e-2 0.01448475
          76.2712 1.54591732e-2 0.01467323
          83.8983 1.39690017e-2 0.01487335
          91.5254 1.27332466e-2 0.01508489
          99.1525 1.16934563e-2 0.01530763
          106.7797 1.08078644e-2 0.01554129
          114.4068 1.00458234e-2 0.01578554
          122.0339 9.38432554e-3 0.01604001
          129.6610 8.80575223e-3 0.01630426
          137.2881 8.29637365e-3 0.01657779
          144.9153 7.84532318e-3 0.01686007
          152.5424 7.44388001e-3 0.01715048
          160.1695 7.08495761e-3 0.01744840
          167.7966 6.76273237e-3 0.01775316
          175.4237 6.47236994e-3 0.01806405
          183.0508 6.20982051e-3 0.01838038
          190.6780 5.97166384e-3 0.01870144
          198.3051 5.75499033e-3 0.01902655
          205.9322 5.55730882e-3 0.01935503
          213.5593 5.37647420e-3 0.01968624
          221.1864 5.21063007e-3 0.02001956
          228.8136 5.05816269e-3 0.02035442
          236.4407 4.91766380e-3 0.02069030
          244.0678 4.78790010e-3 0.02102672
          251.6949 4.66778821e-3 0.02136321
          259.3220 4.55637369e-3 0.02169940
          266.9492 4.45281357e-3 0.02203493
          274.5763 4.35636156e-3 0.02236947
          282.2034 4.26635548e-3 0.02270277
          289.8305 4.18220654e-3 0.02303457
          297.4576 4.10339018e-3 0.02336468
          305.0847 4.02943811e-3 0.02369291
          312.7119 3.95993155e-3 0.02401912
          320.3390 3.89449525e-3 0.02434318
          327.9661 3.83279239e-3 0.02466500
          335.5932 3.77452008e-3 0.02498448
          343.2203 3.71940550e-3 0.02530157
          350.8475 3.66720248e-3 0.02561621
          358.4746 3.61768848e-3 0.02592837
          366.1017 3.57066205e-3 0.02623802
          373.7288 3.52594046e-3 0.02654515
          381.3559 3.48335773e-3 0.02684975
          388.9831 3.44276283e-3 0.02715182
          396.6102 3.40401815e-3 0.02745138
          404.2373 3.36699804e-3 0.02774843
          411.8644 3.33158768e-3 0.02804299
          419.4915 3.29768190e-3 0.02833509
          427.1186 3.26518431e-3 0.02862474
          434.7458 3.23400636e-3 0.02891198
          442.3729 3.20406666e-3 0.02919685
          450.0000 3.17529021e-3 0.02947936 /
        PVTW
          400 1.0 4E-5 0.4 0 /
        DENSITY
          800 1000 0.7951 /
        -- Pore compressibility at the initial pressure — the parameter this
        -- reference exists to arbitrate.
        ROCK
          400 5E-4 /
        -- Corey gas/water curves from the scenario's own end points:
        -- S_wc 0.2, S_gc 0.02, n_g 1.5, n_w 2, k_rg_max 0.9, k_rw_max 0.4.
        SGWFN
          0.000000 0.00000000 0.40000000 0
          0.040000 0.00369527 0.36100000 0
          0.080000 0.01920116 0.32400000 0
          0.120000 0.04131432 0.28900000 0
          0.160000 0.06843727 0.25600000 0
          0.200000 0.09977216 0.22500000 0
          0.240000 0.13481389 0.19600000 0
          0.280000 0.17320508 0.16900000 0
          0.320000 0.21467550 0.14400000 0
          0.360000 0.25901146 0.12100000 0
          0.400000 0.30603845 0.10000000 0
          0.440000 0.35561047 0.08100000 0
          0.480000 0.40760298 0.06400000 0
          0.520000 0.46190814 0.04900000 0
          0.560000 0.51843134 0.03600000 0
          0.600000 0.57708873 0.02500000 0
          0.640000 0.63780532 0.01600000 0
          0.680000 0.70051350 0.00900000 0
          0.720000 0.76515191 0.00400000 0
          0.760000 0.83166454 0.00100000 0
          0.800000 0.90000000 0.00000000 0 /
        REGIONS
        SOLUTION
        -- Datum at the mid-depth of the 20 m section. The gas/water contact is
        -- far below the model, so every cell initialises at connate water.
        EQUIL
          10 400 10000 0 0 0 0 0 0 /
        SUMMARY
        FGPR
        FGPT
        FWPR
        FPR
        FGIP
        RUNSUM
        SEPARATE
        SCHEDULE
        RPTRST
          BASIC=2 /
        -- One producer at the centre of the section, all five layers, on the
        -- same 30 bar abandonment pressure the scenario uses.
        WELSPECS
          'PROD' 'G' 11 1 10 'GAS' /
        /
        COMPDAT
          'PROD' 11 1 1 5 'OPEN' 2* 0.2 /
        /
        WCONPROD
          'PROD' 'OPEN' 'BHP' 5* 30 /
        /
        TSTEP
          200*20 /
        END
"""
    ),
)


# The `gas_injection` base case. Its deck is the small-direct twin that
# `three_phase_gas_injection_matches_opm_flow_twin` grades ResSim against, so the
# chart and the engine test read the same Flow run.
GAS_INJECTION = OpmCase(
    key="gas_injection",
    scenario_key="gas_injection",
    label="Gas Injection (base case, 50 cells)",
    deck_name="GAS_INJECTION.DATA",
    supported_curves=(
        "FOPR", "FWPR", "FWIR", "FOPT", "FWPT", "FWIT", "FPR",
        "FGPR", "FGPT", "FGOR", "FGIR", "FGIT", "FVIT", "WBHP",
    ),
    deck_source="opm/reference-decks/small-direct/go-1d-50/CASE.DATA",
    deck=_committed_deck("opm/reference-decks/small-direct/go-1d-50/CASE.DATA"),
    flow_args=("--enable-gravity=false",),
    origin=ORIGIN_SMALL_DIRECT,
    cumulative_injection_curve="FVIT",
    cumulative_surface_injection_curve="FGIT",
    # 50 x 20 m by 1 x 50 m by 1 x 10 m at 0.2 porosity.
    pore_volume_m3=100_000.0,
    # No gas cut: ResSim's `rates` panel is a surface gas-cut fraction Flow does
    # not report as one vector, and a ratio rebuilt here would be a derived curve
    # presented as Flow output.
    curve_display={
        "FOPR": {"panelKey": "oil_rate", "curveKey": "opm-oil-rate", "label": "OPM Flow — Oil Rate"},
        "FOPT": {"panelKey": "cumulative", "curveKey": "opm-cum-oil", "label": "OPM Flow — Cum Oil"},
        "FPR": {"panelKey": "diagnostics", "curveKey": "opm-avg-pressure", "label": "OPM Flow — Avg Pressure"},
        "FGIT": {"panelKey": "volumes", "curveKey": "opm-cum-injection", "label": "OPM Flow — Cum Gas Injection"},
    },
)


def _dep_pvt_case(variant: str, label: str, key_prefix: str, rung: str) -> OpmCase:
    """One rung of `dep_pvt`'s undersaturated-compressibility ladder.

    Two cases because an artifact carries one run and the pair is the exhibit:
    the same fluid below the bubble point, 2.4x apart in time to reach it.
    """
    deck_path = f"opm/reference-decks/small-direct/dep-pvt-{variant}/CASE.DATA"
    return OpmCase(
        key=f"dep_pvt_{variant.replace('-', '_')}",
        scenario_key="dep_pvt",
        label=label,
        deck_name=f"DEP_PVT_{variant.replace('-', '_').upper()}.DATA",
        supported_curves=("FOPR", "FWPR", "FWIR", "FOPT", "FWPT", "FWIT", "FPR", "FGPR", "FGPT", "FGOR", "WBHP"),
        deck_source=deck_path,
        deck=_committed_deck(deck_path),
        flow_args=("--enable-gravity=false",),
        origin=ORIGIN_SMALL_DIRECT,
        curve_display={
            "FPR": {"panelKey": "diagnostics", "curveKey": f"{key_prefix}avg-pressure", "label": f"OPM Flow — Avg Pressure ({rung})"},
            "FGOR": {"panelKey": "gor", "curveKey": f"{key_prefix}gor", "label": f"OPM Flow — GOR ({rung})"},
            "FGPR": {"panelKey": "gas_rate", "curveKey": f"{key_prefix}gas-rate", "label": f"OPM Flow — Gas Rate ({rung})"},
            "FGPT": {"panelKey": "cumulative_gas", "curveKey": f"{key_prefix}cum-gas", "label": f"OPM Flow — Cum Gas ({rung})"},
        },
    )


DEP_PVT_CORRELATION = _dep_pvt_case(
    "correlation", "PVT Model Risk (correlation c_o = 1.0e-4 /bar, base)", "opm-", "c_o = 1.0e-4",
)
DEP_PVT_LAB_REPORT = _dep_pvt_case(
    "lab-report", "PVT Model Risk (lab-report c_o = 2.5e-4 /bar)", "opm-lab-", "c_o = 2.5e-4",
)


CASES = {case.key: case for case in (
    WF_BL1D, SPE1_GAS_INJECTION, GAS_DRIVE, WF_GRAVITY,
    WF_NUMERICS, WF_NUMERICS_FINE, DEP_GAS_PZ, DEP_GAS_PZ_GEOPRESSURED,
    GAS_INJECTION, DEP_PVT_CORRELATION, DEP_PVT_LAB_REPORT,
)}
