import type { RateChartCurveOverride, RateChartLayoutConfig } from '../charts/rateChartLayoutConfig';

export type PresetCategory = 'depletion' | 'waterflood' | 'exploration';

export type PresetMode = 'dep' | 'wf' | 'sim';

export type PresetLayoutCurveOverride = RateChartCurveOverride;

export type PresetLayoutConfig = RateChartLayoutConfig;

type SourcePresetDefinition = {
    key: string;
    category: PresetCategory;
    mode: PresetMode;
    label: string;
    description: string;
    params: Record<string, any>;
    layoutConfig?: PresetLayoutConfig;
};

export type PresetEntry = SourcePresetDefinition;

export type PresetDimensionOption = {
    value: string;
    label: string;
    description: string;
};

const sourcePresetDefinitions: SourcePresetDefinition[] = [
    {
        "key": "depletion_corner_producer",
        "category": "depletion",
        "mode": "dep",
        "label": "Corner Producer (1D)",
        "description": "1D depletion with producer at corner — linear geometry",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": false,
            "injectorControlMode": "pressure",
            "producerControlMode": "pressure",
            "injectorBhp": 500,
            "producerBhp": 80,
            "targetInjectorRate": 350,
            "targetProducerRate": 350,
            "reservoirPorosity": 0.2,
            "nx": 48,
            "ny": 1,
            "nz": 1,
            "cellDx": 10,
            "cellDy": 10,
            "cellDz": 5,
            "delta_t_days": 0.5,
            "steps": 36,
            "max_sat_change_per_step": 0.1,
            "initialPressure": 300,
            "initialSaturation": 0.1,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 0,
            "producerJ": 0,
            "permMode": "uniform",
            "uniformPermX": 100,
            "uniformPermY": 100,
            "uniformPermZ": 10,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2
        },
        "layoutConfig": {
            "rateChart": {
                "logScale": true,
                "curves": {
                    "Water Cut (Sim)": {
                        "disabled": true
                    },
                    "Water Cut (Reference Solution)": {
                        "disabled": true
                    }
                }
            }
        }
    },
    {
        "key": "depletion_center_producer",
        "category": "depletion",
        "mode": "dep",
        "label": "Center Producer (2D)",
        "description": "2D depletion with producer at centre — radial geometry",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": false,
            "injectorControlMode": "pressure",
            "producerControlMode": "pressure",
            "injectorBhp": 500,
            "producerBhp": 80,
            "targetInjectorRate": 350,
            "targetProducerRate": 350,
            "reservoirPorosity": 0.2,
            "nx": 49,
            "ny": 49,
            "nz": 1,
            "cellDx": 10,
            "cellDy": 10,
            "cellDz": 5,
            "delta_t_days": 2,
            "steps": 50,
            "max_sat_change_per_step": 0.1,
            "initialPressure": 300,
            "initialSaturation": 0.1,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 24,
            "producerJ": 24,
            "permMode": "uniform",
            "uniformPermX": 100,
            "uniformPermY": 100,
            "uniformPermZ": 10,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2
        }
    },
    {
        "key": "depletion_1d_clean",
        "category": "depletion",
        "mode": "dep",
        "label": "Clean 1D Depletion",
        "description": "Sw=Swc, no capillary — ideal for analytical match",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": false,
            "injectorControlMode": "pressure",
            "producerControlMode": "pressure",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 350,
            "targetProducerRate": 350,
            "reservoirPorosity": 0.2,
            "nx": 20,
            "ny": 1,
            "nz": 1,
            "cellDx": 10,
            "cellDy": 10,
            "cellDz": 10,
            "delta_t_days": 1,
            "steps": 50,
            "max_sat_change_per_step": 0.1,
            "initialPressure": 300,
            "initialSaturation": 0.1,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 0,
            "producerJ": 0,
            "permMode": "uniform",
            "uniformPermX": 200,
            "uniformPermY": 200,
            "uniformPermZ": 20,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2
        }
    },
    {
        "key": "depletion_2d_radial_clean",
        "category": "depletion",
        "mode": "dep",
        "label": "Clean 2D Radial Depletion",
        "description": "Center producer, Sw=Swc, no capillary — radial analytical match",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": false,
            "injectorControlMode": "pressure",
            "producerControlMode": "pressure",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 350,
            "targetProducerRate": 350,
            "reservoirPorosity": 0.2,
            "nx": 21,
            "ny": 21,
            "nz": 1,
            "cellDx": 10,
            "cellDy": 10,
            "cellDz": 10,
            "delta_t_days": 2,
            "steps": 50,
            "max_sat_change_per_step": 0.1,
            "initialPressure": 300,
            "initialSaturation": 0.1,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 10,
            "producerJ": 10,
            "permMode": "uniform",
            "uniformPermX": 200,
            "uniformPermY": 200,
            "uniformPermZ": 20,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2
        }
    },
    {
        "key": "bl_aligned_homogeneous",
        "category": "waterflood",
        "mode": "wf",
        "label": "BL Aligned — Homogeneous",
        "description": "48-cell homogeneous 1D-like waterflood",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "rate",
            "producerControlMode": "rate",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 250,
            "targetProducerRate": 250,
            "reservoirPorosity": 0.2,
            "nx": 48,
            "ny": 1,
            "nz": 1,
            "cellDx": 5,
            "cellDy": 10,
            "cellDz": 10,
            "delta_t_days": 0.5,
            "steps": 50,
            "max_sat_change_per_step": 0.05,
            "initialPressure": 300,
            "initialSaturation": 0.2,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2,
            "permMode": "uniform",
            "uniformPermX": 150,
            "uniformPermY": 150,
            "uniformPermZ": 150,
            "rateControlledWells": true,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 47,
            "producerJ": 0
        }
    },
    {
        "key": "bl_aligned_mild_capillary",
        "category": "waterflood",
        "mode": "wf",
        "label": "BL Aligned — Mild Capillary",
        "description": "48-cell with mild capillary pressure",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "rate",
            "producerControlMode": "rate",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 250,
            "targetProducerRate": 250,
            "reservoirPorosity": 0.2,
            "nx": 48,
            "ny": 1,
            "nz": 1,
            "cellDx": 5,
            "cellDy": 10,
            "cellDz": 10,
            "delta_t_days": 0.5,
            "steps": 50,
            "max_sat_change_per_step": 0.05,
            "initialPressure": 300,
            "initialSaturation": 0.2,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": true,
            "capillaryPEntry": 0.75,
            "capillaryLambda": 3.2,
            "permMode": "uniform",
            "uniformPermX": 150,
            "uniformPermY": 150,
            "uniformPermZ": 150,
            "rateControlledWells": true,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 47,
            "producerJ": 0
        }
    },
    {
        "key": "bl_aligned_mobility_balanced",
        "category": "waterflood",
        "mode": "wf",
        "label": "BL Aligned — Mobility Balanced",
        "description": "48-cell with balanced mobility ratio",
        "params": {
            "mu_w": 0.8,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "rate",
            "producerControlMode": "rate",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 250,
            "targetProducerRate": 250,
            "reservoirPorosity": 0.2,
            "nx": 48,
            "ny": 1,
            "nz": 1,
            "cellDx": 5,
            "cellDy": 10,
            "cellDz": 10,
            "delta_t_days": 0.5,
            "steps": 50,
            "max_sat_change_per_step": 0.05,
            "initialPressure": 300,
            "initialSaturation": 0.2,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2.1,
            "n_o": 1.9,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2,
            "permMode": "uniform",
            "uniformPermX": 150,
            "uniformPermY": 150,
            "uniformPermZ": 150,
            "rateControlledWells": true,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 47,
            "producerJ": 0
        }
    },
    {
        "key": "waterflood_bl_clean",
        "category": "waterflood",
        "mode": "wf",
        "label": "BL Clean — Ideal Match",
        "description": "Sw=Swc, no capillary, rate-controlled — cleanest BL comparison",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "rate",
            "producerControlMode": "rate",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 200,
            "targetProducerRate": 200,
            "reservoirPorosity": 0.2,
            "nx": 48,
            "ny": 1,
            "nz": 1,
            "cellDx": 5,
            "cellDy": 10,
            "cellDz": 10,
            "delta_t_days": 0.5,
            "steps": 50,
            "max_sat_change_per_step": 0.05,
            "initialPressure": 300,
            "initialSaturation": 0.1,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2,
            "permMode": "uniform",
            "uniformPermX": 500,
            "uniformPermY": 500,
            "uniformPermZ": 50,
            "rateControlledWells": true,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 47,
            "producerJ": 0
        }
    },
    {
        "key": "waterflood_unfavorable_mobility",
        "category": "waterflood",
        "mode": "wf",
        "label": "BL Unfavorable Mobility",
        "description": "High oil viscosity (M≈17) — early breakthrough",
        "params": {
            "mu_w": 0.3,
            "mu_o": 5,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "rate",
            "producerControlMode": "rate",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 200,
            "targetProducerRate": 200,
            "reservoirPorosity": 0.2,
            "nx": 48,
            "ny": 1,
            "nz": 1,
            "cellDx": 5,
            "cellDy": 10,
            "cellDz": 10,
            "delta_t_days": 0.5,
            "steps": 50,
            "max_sat_change_per_step": 0.05,
            "initialPressure": 300,
            "initialSaturation": 0.1,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "gravityEnabled": false,
            "capillaryEnabled": false,
            "capillaryPEntry": 0,
            "capillaryLambda": 2,
            "permMode": "uniform",
            "uniformPermX": 500,
            "uniformPermY": 500,
            "uniformPermZ": 50,
            "rateControlledWells": true,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 47,
            "producerJ": 0
        }
    },
    {
        "key": "baseline_waterflood",
        "category": "exploration",
        "mode": "sim",
        "label": "Baseline Waterflood",
        "description": "Random heterogeneity with capillary pressure",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "pressure",
            "producerControlMode": "pressure",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 350,
            "targetProducerRate": 350,
            "reservoirPorosity": 0.2,
            "nx": 15,
            "ny": 10,
            "nz": 10,
            "cellDx": 10,
            "cellDy": 10,
            "cellDz": 1,
            "delta_t_days": 0.25,
            "steps": 20,
            "max_sat_change_per_step": 0.1,
            "initialPressure": 300,
            "initialSaturation": 0.3,
            "s_wc": 0.1,
            "s_or": 0.1,
            "n_w": 2,
            "n_o": 2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "capillaryEnabled": true,
            "capillaryPEntry": 5,
            "capillaryLambda": 2,
            "permMode": "random",
            "minPerm": 50,
            "maxPerm": 200,
            "useRandomSeed": true,
            "randomSeed": 12345,
            "gravityEnabled": false,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 14,
            "producerJ": 0
        }
    },
    {
        "key": "high_contrast_layers",
        "category": "exploration",
        "mode": "sim",
        "label": "High Contrast Layers",
        "description": "Layered permeability with 10x contrast and strong capillary",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "pressure",
            "producerControlMode": "pressure",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 350,
            "targetProducerRate": 350,
            "reservoirPorosity": 0.2,
            "nx": 15,
            "ny": 10,
            "nz": 10,
            "cellDx": 10,
            "cellDy": 10,
            "cellDz": 1,
            "delta_t_days": 0.25,
            "steps": 20,
            "max_sat_change_per_step": 0.1,
            "initialPressure": 320,
            "initialSaturation": 0.25,
            "s_wc": 0.12,
            "s_or": 0.12,
            "n_w": 2.2,
            "n_o": 2.2,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "capillaryEnabled": true,
            "capillaryPEntry": 8,
            "capillaryLambda": 2.5,
            "permMode": "perLayer",
            "layerPermsX": [30, 40, 60, 90, 150, 400, 150, 90, 60, 40],
            "layerPermsY": [30, 40, 60, 90, 150, 400, 150, 90, 60, 40],
            "layerPermsZ": [3, 4, 6, 9, 15, 40, 15, 9, 6, 4],
            "gravityEnabled": false,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 14,
            "producerJ": 0
        }
    },
    {
        "key": "viscous_fingering_risk",
        "category": "exploration",
        "mode": "sim",
        "label": "Viscous Fingering Risk",
        "description": "Unfavourable mobility ratio with strong heterogeneity",
        "params": {
            "mu_w": 0.5,
            "mu_o": 1,
            "c_o": 0.00001,
            "c_w": 0.000003,
            "rock_compressibility": 0.000001,
            "depth_reference": 0,
            "volume_expansion_o": 1,
            "volume_expansion_w": 1,
            "rho_w": 1000,
            "rho_o": 800,
            "well_radius": 0.1,
            "well_skin": 0,
            "max_pressure_change_per_step": 75,
            "max_well_rate_change_fraction": 0.75,
            "injectorEnabled": true,
            "injectorControlMode": "pressure",
            "producerControlMode": "pressure",
            "injectorBhp": 500,
            "producerBhp": 100,
            "targetInjectorRate": 350,
            "targetProducerRate": 350,
            "reservoirPorosity": 0.2,
            "nx": 15,
            "ny": 10,
            "nz": 10,
            "cellDx": 10,
            "cellDy": 10,
            "cellDz": 1,
            "delta_t_days": 0.25,
            "steps": 20,
            "max_sat_change_per_step": 0.1,
            "initialPressure": 280,
            "initialSaturation": 0.2,
            "s_wc": 0.08,
            "s_or": 0.15,
            "n_w": 1.6,
            "n_o": 2.4,
            "k_rw_max": 1,
            "k_ro_max": 1,
            "capillaryEnabled": true,
            "capillaryPEntry": 3,
            "capillaryLambda": 1.6,
            "permMode": "random",
            "minPerm": 20,
            "maxPerm": 500,
            "useRandomSeed": true,
            "randomSeed": 987654,
            "gravityEnabled": false,
            "injectorI": 0,
            "injectorJ": 0,
            "producerI": 14,
            "producerJ": 0
        }
    }
];

export const presetCases: PresetEntry[] = sourcePresetDefinitions.map((entry) => ({ ...entry }));

const presetEntryMap = new Map(presetCases.map((entry) => [entry.key, entry]));

const presetCasesByMode = new Map<PresetMode, PresetEntry[]>([
    ['dep', presetCases.filter((entry) => entry.mode === 'dep')],
    ['wf', presetCases.filter((entry) => entry.mode === 'wf')],
    ['sim', presetCases.filter((entry) => entry.mode === 'sim')],
]);

const presetCasesByCategory = new Map<PresetCategory, PresetEntry[]>([
    ['depletion', presetCases.filter((entry) => entry.category === 'depletion')],
    ['waterflood', presetCases.filter((entry) => entry.category === 'waterflood')],
    ['exploration', presetCases.filter((entry) => entry.category === 'exploration')],
]);

export function getPresetEntry(key: string | null | undefined): PresetEntry | null {
    if (!key) return null;
    return presetEntryMap.get(key) ?? null;
}

export function getPresetEntriesForMode(mode: PresetMode | null | undefined): PresetEntry[] {
    if (!mode) return [];
    return presetCasesByMode.get(mode) ?? [];
}

export function getPresetEntriesForCategory(category: PresetCategory | null | undefined): PresetEntry[] {
    if (!category) return [];
    return presetCasesByCategory.get(category) ?? [];
}

export function getPresetDimensionOptions(mode: PresetMode | null | undefined): PresetDimensionOption[] {
    return getPresetEntriesForMode(mode).map((entry) => ({
        value: entry.key,
        label: entry.label,
        description: entry.description,
    }));
}