import type { ModePanelParameterBindings } from "../ui/modePanelTypes";

export type ReservoirPreset = {
  key: string;
  label: string;
  description: string;
  params: Partial<ModePanelParameterBindings>;
};

export const RESERVOIR_PRESETS: readonly ReservoirPreset[] = [
  {
    key: "sandstone",
    label: "Sandstone",
    description: "Conventional sandstone reservoir (high perm, moderate porosity)",
    params: {
      reservoirPorosity: 0.22,
      uniformPermX: 200,
      uniformPermY: 200,
      uniformPermZ: 20,
      permMode: "uniform",
      mu_o: 2.0,
      mu_w: 0.5,
      rho_o: 800,
      rho_w: 1020,
      c_o: 1.5e-5,
      c_w: 4.5e-6,
      rock_compressibility: 5e-6,
      initialPressure: 250,
      s_wc: 0.20,
      s_or: 0.20,
      n_w: 3.0,
      n_o: 2.0,
      capillaryPEntry: 0.5,
      capillaryLambda: 2.0,
    },
  },
  {
    key: "carbonate",
    label: "Carbonate",
    description: "Carbonate reservoir (variable perm, lower porosity, oil-wet tendency)",
    params: {
      reservoirPorosity: 0.12,
      uniformPermX: 50,
      uniformPermY: 50,
      uniformPermZ: 5,
      permMode: "uniform",
      mu_o: 1.0,
      mu_w: 0.4,
      rho_o: 780,
      rho_w: 1030,
      c_o: 1.2e-5,
      c_w: 4.0e-6,
      rock_compressibility: 8e-6,
      initialPressure: 300,
      s_wc: 0.10,
      s_or: 0.30,
      n_w: 2.0,
      n_o: 4.0,
      k_rw_max: 0.3,
      k_ro_max: 1.0,
      capillaryPEntry: 3.0,
      capillaryLambda: 1.5,
    },
  },
  {
    key: "shale",
    label: "Shale / Tight",
    description: "Tight/shale reservoir (very low perm, low porosity)",
    params: {
      reservoirPorosity: 0.06,
      uniformPermX: 0.1,
      uniformPermY: 0.1,
      uniformPermZ: 0.01,
      permMode: "uniform",
      mu_o: 0.5,
      mu_w: 0.3,
      rho_o: 750,
      rho_w: 1010,
      c_o: 2.0e-5,
      c_w: 4.5e-6,
      rock_compressibility: 3e-6,
      initialPressure: 400,
      s_wc: 0.30,
      s_or: 0.35,
      n_w: 4.0,
      n_o: 2.0,
      k_rw_max: 0.15,
      k_ro_max: 1.0,
      capillaryPEntry: 20.0,
      capillaryLambda: 1.0,
    },
  },
  {
    key: "heavy_oil",
    label: "Heavy Oil",
    description: "Heavy oil sand (high perm, high viscosity, strong water-wet)",
    params: {
      reservoirPorosity: 0.30,
      uniformPermX: 2000,
      uniformPermY: 2000,
      uniformPermZ: 400,
      permMode: "uniform",
      mu_o: 100.0,
      mu_w: 0.5,
      rho_o: 950,
      rho_w: 1010,
      c_o: 1.0e-5,
      c_w: 4.5e-6,
      rock_compressibility: 1e-5,
      initialPressure: 150,
      s_wc: 0.15,
      s_or: 0.15,
      n_w: 2.5,
      n_o: 1.5,
      k_rw_max: 0.8,
      k_ro_max: 1.0,
      capillaryPEntry: 0.2,
      capillaryLambda: 3.0,
    },
  },
] as const;
