/**
 * The run-quantity contract: one machine-readable description of what a run can plot.
 *
 * A notebook that wants "the same curves the app shows" needs three things to agree: the set of
 * quantities, what each is called and measured in, and which derived series each one reads. Today
 * that knowledge lives only in `RUN_QUANTITIES`, in TypeScript, reachable only from the bundle —
 * so a Python consumer has no choice but to re-declare it and hope.
 *
 * This test **derives** the contract rather than restating it, then asserts the checked-in file
 * matches. The derivation is mechanical: each quantity's `source` is invoked against a Proxy that
 * records which `DerivedRunSeries` key it touches, so the mapping cannot be mis-transcribed and
 * cannot silently drift. Adding a quantity, renaming a series field or changing a unit fails here
 * with the regeneration command, which is the point — the contract is generated, and the failure
 * is the reminder.
 *
 * Deliberately *not* included: how each series is computed. That is `buildDerivedRunSeries`, it
 * needs case inputs beyond the rate history, and a conformance check is the honest way to keep a
 * second implementation agreeing with it — not a schema field claiming it does.
 */
import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { RUN_QUANTITIES } from './runQuantities';
import type { DerivedRunSeries } from './axisAdapters';

const CONTRACT_PATH = path.join('contracts', 'run-quantities.json');

/** Which `DerivedRunSeries` key does this quantity read? Ask it, rather than being told. */
function seriesKeyOf(source: (derived: DerivedRunSeries) => unknown): string {
    const touched: string[] = [];
    const probe = new Proxy(
        {},
        {
            get(_target, key) {
                if (typeof key === 'string') touched.push(key);
                return [];
            },
        },
    ) as DerivedRunSeries;
    source(probe);
    if (touched.length !== 1) {
        throw new Error(
            `expected a quantity to read exactly one derived series key, saw [${touched.join(', ')}]`,
        );
    }
    return touched[0];
}

function buildContract() {
    return {
        $comment:
            'GENERATED by src/lib/charts/runQuantities.contract.test.ts. Do not edit by hand. ' +
            'Regenerate with RESSIM_WRITE_CONTRACT=1 npx vitest run src/lib/charts/runQuantities.contract.test.ts',
        quantities: Object.values(RUN_QUANTITIES)
            .map((q) => ({
                id: q.id,
                label: q.label,
                unit: q.unit,
                property: q.property,
                series: seriesKeyOf(q.source),
            }))
            .sort((a, b) => a.id.localeCompare(b.id)),
    };
}

describe('run-quantity contract', () => {
    it('derives a series key for every quantity', () => {
        const contract = buildContract();
        expect(contract.quantities.length).toBe(Object.keys(RUN_QUANTITIES).length);
        for (const q of contract.quantities) {
            expect(q.series, `${q.id} has no derived series key`).toBeTruthy();
        }
    });

    it('matches the checked-in contract file', () => {
        const contract = buildContract();
        const serialized = `${JSON.stringify(contract, null, 2)}\n`;

        if (process.env.RESSIM_WRITE_CONTRACT) {
            fs.mkdirSync(path.dirname(CONTRACT_PATH), { recursive: true });
            fs.writeFileSync(CONTRACT_PATH, serialized);
        }

        expect(
            fs.existsSync(CONTRACT_PATH),
            `${CONTRACT_PATH} is missing; regenerate with RESSIM_WRITE_CONTRACT=1`,
        ).toBe(true);
        expect(
            fs.readFileSync(CONTRACT_PATH, 'utf8'),
            `${CONTRACT_PATH} is stale. Regenerate with:\n` +
                '  RESSIM_WRITE_CONTRACT=1 npx vitest run src/lib/charts/runQuantities.contract.test.ts',
        ).toBe(serialized);
    });
});
