import type { PresetEntry } from '../presetCases';

export const baseline_waterflood: PresetEntry = {
    "key": "baseline_waterflood",
    "category": "exploration",
    "mode": "sim",
    "label": "Baseline Waterflood",
    "description": "Random heterogeneity with capillary pressure",
    "params": {
        "mu_w": 0.5,
        "mu_o": 1,
        "c_o": 0.00001,
        "c_w": 0.000003,
        "rock_compressibility": 0.000001,
        "depth_reference": 0,
        "volume_expansion_o": 1,
        "volume_expansion_w": 1,
        "rho_w": 1000,
        "rho_o": 800,
        "well_radius": 0.1,
        "well_skin": 0,
        "max_pressure_change_per_step": 75,
        "max_well_rate_change_fraction": 0.75,
        "injectorEnabled": true,
        "injectorControlMode": "pressure",
        "producerControlMode": "pressure",
        "injectorBhp": 500,
        "producerBhp": 100,
        "targetInjectorRate": 350,
        "targetProducerRate": 350,
        "reservoirPorosity": 0.2,
        "nx": 15,
        "ny": 10,
        "nz": 10,
        "cellDx": 10,
        "cellDy": 10,
        "cellDz": 1,
        "delta_t_days": 0.25,
        "steps": 20,
        "max_sat_change_per_step": 0.1,
        "initialPressure": 300,
        "initialSaturation": 0.3,
        "s_wc": 0.1,
        "s_or": 0.1,
        "n_w": 2,
        "n_o": 2,
        "k_rw_max": 1,
        "k_ro_max": 1,
        "capillaryEnabled": true,
        "capillaryPEntry": 5,
        "capillaryLambda": 2,
        "permMode": "random",
        "minPerm": 50,
        "maxPerm": 200,
        "useRandomSeed": true,
        "randomSeed": 12345,
        "gravityEnabled": false,
        "injectorI": 0,
        "injectorJ": 0,
        "producerI": 14,
        "producerJ": 0
    }
};
