import type { PresetEntry } from '../presetCases';

export const bl_aligned_mild_capillary: PresetEntry = {
    "key": "bl_aligned_mild_capillary",
    "category": "waterflood",
    "mode": "wf",
    "label": "BL Aligned — Mild Capillary",
    "description": "48-cell with mild capillary pressure",
    "params": {
        "mu_w": 0.5,
        "mu_o": 1,
        "c_o": 0.00001,
        "c_w": 0.000003,
        "rock_compressibility": 0.000001,
        "depth_reference": 0,
        "volume_expansion_o": 1,
        "volume_expansion_w": 1,
        "rho_w": 1000,
        "rho_o": 800,
        "well_radius": 0.1,
        "well_skin": 0,
        "max_pressure_change_per_step": 75,
        "max_well_rate_change_fraction": 0.75,
        "injectorEnabled": true,
        "injectorControlMode": "rate",
        "producerControlMode": "rate",
        "injectorBhp": 500,
        "producerBhp": 100,
        "targetInjectorRate": 250,
        "targetProducerRate": 250,
        "reservoirPorosity": 0.2,
        "nx": 48,
        "ny": 1,
        "nz": 1,
        "cellDx": 5,
        "cellDy": 10,
        "cellDz": 10,
        "delta_t_days": 0.5,
        "steps": 50,
        "max_sat_change_per_step": 0.05,
        "initialPressure": 300,
        "initialSaturation": 0.2,
        "s_wc": 0.1,
        "s_or": 0.1,
        "n_w": 2,
        "n_o": 2,
        "k_rw_max": 1,
        "k_ro_max": 1,
        "gravityEnabled": false,
        "capillaryEnabled": true,
        "capillaryPEntry": 0.75,
        "capillaryLambda": 3.2,
        "permMode": "uniform",
        "uniformPermX": 150,
        "uniformPermY": 150,
        "uniformPermZ": 150,
        "rateControlledWells": true,
        "injectorI": 0,
        "injectorJ": 0,
        "producerI": 47,
        "producerJ": 0
    }
};
