import type { PresetEntry } from '../presetCases';

export const high_contrast_layers: PresetEntry = {
    "key": "high_contrast_layers",
    "category": "exploration",
    "mode": "sim",
    "label": "High Contrast Layers",
    "description": "Layered permeability with 10x contrast and strong capillary",
    "params": {
        "mu_w": 0.5,
        "mu_o": 1,
        "c_o": 0.00001,
        "c_w": 0.000003,
        "rock_compressibility": 0.000001,
        "depth_reference": 0,
        "volume_expansion_o": 1,
        "volume_expansion_w": 1,
        "rho_w": 1000,
        "rho_o": 800,
        "well_radius": 0.1,
        "well_skin": 0,
        "max_pressure_change_per_step": 75,
        "max_well_rate_change_fraction": 0.75,
        "injectorEnabled": true,
        "injectorControlMode": "pressure",
        "producerControlMode": "pressure",
        "injectorBhp": 500,
        "producerBhp": 100,
        "targetInjectorRate": 350,
        "targetProducerRate": 350,
        "reservoirPorosity": 0.2,
        "nx": 15,
        "ny": 10,
        "nz": 10,
        "cellDx": 10,
        "cellDy": 10,
        "cellDz": 1,
        "delta_t_days": 0.25,
        "steps": 20,
        "max_sat_change_per_step": 0.1,
        "initialPressure": 320,
        "initialSaturation": 0.25,
        "s_wc": 0.12,
        "s_or": 0.12,
        "n_w": 2.2,
        "n_o": 2.2,
        "k_rw_max": 1,
        "k_ro_max": 1,
        "capillaryEnabled": true,
        "capillaryPEntry": 8,
        "capillaryLambda": 2.5,
        "permMode": "perLayer",
        "layerPermsX": [30, 40, 60, 90, 150, 400, 150, 90, 60, 40],
        "layerPermsY": [30, 40, 60, 90, 150, 400, 150, 90, 60, 40],
        "layerPermsZ": [3, 4, 6, 9, 15, 40, 15, 9, 6, 4],
        "gravityEnabled": false,
        "injectorI": 0,
        "injectorJ": 0,
        "producerI": 14,
        "producerJ": 0
    }
};
